- docs/operating/databases/mysql.md
> Correct header

- README.md
Workaround for https://github.com/fnproject/fn/issues/391
> Update README to point people away from brew

- README.md
This reverts commit 2f1721c757143c600ac7c87bb51e047590c323ff.
> Revert "Update README to point people away from brew"

- docs/developers/clients.md
> fix url in client libraries for java language wrapper

- .circleci/config.yml
copied https://github.com/fnproject/cli/pull/71
> don't run release on forks

- docs/developers/clients.md
- examples/formats/http/go/README.md
gonna stick examples over in that repo
> add fdk-go to main docs

- api/agent/protocol/json.go
- api/agent/protocol/json_test.go
- examples/formats/json/go/func.go
this patch adds HTTP query string into payload (see more TODOs in code)
adds one more test to verify query
> JSON protocol updating

- CONTRIBUTING.md
This defines what should go in this repo and what shouldn't. Feedback welcome. 
I will be following up with examples of easy ways to add extensions and rebuild the server.
> Rules of fn core

- docs/swagger.yml
> Fixing swagger-doc

- docs/swagger.yml
Swagger generator is a source of a mystery. It doesn't like what swagger.io (no matter would that be OpenAPI v2 or v3) docs saying =/
Even
.
.
.
.
P.S.: @treeder @rdallman i'm unable to to update all clients because don't have appropriate rights to  push code
> Revert swagger back with some fixes

- examples/tutorial/README.md
Hot formats were moved.
Closes: #451
> Fixing links to hot samples

- api/agent/func_logger.go
our dear friend mr. funclogger was bypassing calls to our multi writer since
we were embedding a *bytes.Buffer, it was using ReadFrom and WriteString which
would never call the stderr logger's Write method (or, as I learned, other
things trying to wrap that buffer's Write method...).
the tl;dr is many times DEBUG lines don't get spat out, from async tasks
especially (few people using this).
I think the final solution is probably to make funclogger a 'more robust'
interface that we understand instead of trying to minimize it to an
io.ReaderWriterCloser, much like how bytes.Buffer has all kinds of
methods implemented on it, we can implement things like ReadFrom and
WriteString most likely. not a big fan of how things are now (and it's my own
doing) with the readerwritercloser coming from …
> fix debug logger output

- api/server/prom_zip_collector.go
This PR is intended to provide a fix to https://github.com/fnproject/fn/issues/464
That bug reports that in some (unknown) circumstances, the Prometheus go client is complaining that the Fn server is attempting to record a metric which has a different number of labels than it did when it was first sent. 
I haven't been able to reproduce this. The only way I can think of that might cause this error is that spans of a particular name are sometimes created with a parent span which has fn_appname and fn_path set, and are sometimes created without a parent span. However I haven't found how this might happen. 
Whatever the cause, this PR is intended to prevent something like this causing "inconsistent cardinaliity errors". When a metric is first created (e.g. the first time a span with a …
> Add protection against inconsistent cardinaliity errors

- Dockerfile
- docs/operating/options.md
> Rollback dockerfile (image too big) and add docker run command to docs.

- docs/operating/kubernetes/README.md
- docs/operating/kubernetes/fn-service.yaml
Addresses https://github.com/fnproject/fn/issues/491 and a couple of minor things (typo, fix path, etc.)
Quick fix until we have a Helm chart.
> K8s docs update

- fnlb/lb/allgrouper.go
*) Any new node now by default is in unknown state.
*) One health check is required for unknown state to move in
to healthy/unhealthy states, then actual interval and
thresholds apply.
*) add() no longer runs health check as this is now handled
with the new logic.
This means during restarts fnlb will run one health check
immediately for nodes to switch to healthy/unhealthy state
to ensure speedy start, but guard against routing traffic to
unhealthy servers. After this initial state, nodes are
subjected to regular interval and thresholds.
> fn: fnlb: default health state for new nodes

- api/server/prom_zip_collector.go
*) Added mutex to guard against concurrent access to maps
> fn: prometheus collector concurrent map access

- fnlb/lb/allgrouper_test.go
*) localhost to avoid http proxy interception
closes #527
> fn: fnlb: fix tests if behind http proxy

- api/agent/protocol/factory.go
- api/agent/protocol/json_test.go
> Use valid call type instead in protocol

- README.md
- docker-compose.yml
- docs/README.md
- docs/operating/compose.md
- examples/grafana/prometheus.yml
> Docker compose file for simpler dev env

- Makefile
- README.md
- api/server/server.go
- api_test.sh
- build.ps1
- docs/definitions.md
- docs/operating/databases/README.md
- docs/operating/databases/mysql.md
- docs/operating/databases/postgres.md
- docs/operating/kubernetes/README.md
- docs/operating/kubernetes/fn-service.yaml
- docs/operating/logs/README.md
- docs/operating/mqs/README.md
- docs/operating/options.md
- docs/operating/ui.md
- fnlb/README.md
- test/fn-api-tests/README.md
- test/fn-api-tests/utils.go
We decide to prefix with FN whatever we'd like to prefix except DOCKER_HOST which should remain the same.
Closes: #492
> Fn-prefix everything

- api/models/error.go
As per https://github.com/fnproject/fn/issues/548
> Nitfix for #548

- docs/swagger.yml
Can't build new client without this one in master =/
> New swagger version: 0.2.2

- api/agent/agent.go
- api/agent/agent_test.go
- api/agent/async.go
- api/agent/call.go
- api/agent/data_access.go
- api/agent/drivers/docker/docker_client.go
- api/common/backoff.go
- api/datastore/internal/datastoretest/test.go
- api/datastore/internal/datastoreutil/metrics.go
- api/datastore/mock.go
- api/datastore/sql/sql.go
- api/models/datastore.go
- api/models/error.go
- api/server/apps_test.go
- api/server/calls_test.go
- api/server/hybrid.go
- api/server/middleware_test.go
- api/server/routes_test.go
- api/server/runner.go
- api/server/runner_async_test.go
- api/server/runner_test.go
- api/server/server.go
- api/server/server_test.go
- clients/hybrid/client.go
- docs/developers/hybrid.md
- test/fn-api-tests/utils.go
gonna try to land this so we can start PR'ing off of master to coordinate. this is 3 people's work from the hybrid-api branch but updated with some changes from master since that branch was getting stale. i rebased and you don't have to forgive me :(
with this we can probably start iterating much easier since a lot of the layers are in place now. gonna post comments in #531 but code seems like it won't break master
> hybrid mergy

- docker-compose.yml
plus better volume source path reference for prometheus
> Adding minio for log store in compose

- api/server/init.go
- api/server/server.go
from #593 (but not that issue, as described)
> makes span use init() to run before server.New

- api/server/server.go
> loggy loo for node type on startup

- api/agent/agent.go
This is a correction to the change I made earlier to add two additional tracing spans: `agent_submit_app` and `agent_submit_global`.
`agent_submit_app` should have the BaggageItem `fn_appname` set but not `fn_path`. `agent_submit_global` should have neither.
However I've discovered that for sync functions, these spans inherit   `fn_appname` and `fn_path` from a parent span, `server_http`. This doesn't happen for async functions, whch is why I missed thi suntil I wrote some more tests recently.
The fix is for these two spans to have no parent. This is fine: these spans are special and just to support the `ext-metriocs` extension. The same operation still has a `agent_submit` span which has a parent as usual and has both   `fn_appname` and `fn_path` set.
> Fix spans for prometheus

- api/agent/agent_test.go
- api/agent/call.go
- api/server/runner_test.go
> Async hot hdr fix

- docs/faq.md
I made the requested changes and added the Flow FAQ questions to the end. I tried to simplify the "How do I Upgrade the FDK" question and not sure if I helped or just mucked it up.
> Update faq.md with more Questions

- .circleci/config.yml
- Makefile
- api_test.sh
- images/fn-test-utils/release.sh
- test.sh
*) Moved more tasks into Makefile to allow for
parallelism and dependency checks.
*) Added cpu count in circleci make invocations
for parallelism
*) Fixed broken api-tests for sqlite3 (shell script ignored sqlite typo)
> fn: circleci and makefile adjustments

- api/server/runner_test.go
> fn: tests: revert a hack for agent shutdown

- api/agent/agent.go
- api/agent/call.go
Since by policy we require timeout/2 remaining time
before we can execute the request, we should also
bound the slot wait time by timeout/2 to avoid
waiting for full timeout in slot wait phase.
> fn: agent slot and execution wait correction

- README.md
Here is the Nav for the main ReadMe.md as requested by Shaun. I also fixed a couple of typos. Also, found out Functions-as-a-Service is indeed hyphenated when used as an adjective and added capitalization. 
Mike W.
> Add nav to Readme.md. Fix typos

- api/agent/agent.go
- api/agent/slots.go
- api/agent/slots_test.go
*) revert executor wait queue size comparison. This is too
aggresive and with stall check below, now unnecessary.
*) new container logic now checks if stats are constant, if
this is the case, then we assume the system is stalled (eg
running functions that take long time), this means we need
to make progress and spin up a new container.
> fn: new container lauch adjustments

- api/agent/agent.go
since we were sending a signal before checking if a slot was available, even
in the case of serial calls locally I was seeing 2 containers launch. if we
only send a signal after first checking if a slot is available, this goes
away. 1 usec should not be too offensive of an additional wait, all things
considered here.
> if a slot is available, don't launch more

- .circleci/config.yml
- Makefile
- images/dind/preentry.sh
*To release this:*
Ensure that fnproject/dind:17.12 is rebuilt *and published* first.
At that point the release process should grab it and build a new fnproject/fnserver based off it.
> Ensure we have the latest fnproject/dind

- api/agent/agent.go
- api/agent/slots.go
- api/agent/slots_test.go
*) Stopped using latency previous/current stats, this
was not working as expected. Fresh started agent usually has
these stats as zero for a long time, and initial samples
are high due to downloads, caches, etc.
*) New state to track: containers that are idle. In other
words, containers that have an unused token in the slot
queue.
*) Removed latency counts that used to ignore initial samples,
since these are not used in container start decision anymore.
Also simplifies logs.
*) isNewContainerNeeded() simplified to use idle count
to estimate effective waiters. Removed speculative
latency based logic and progress check comparison.
In agent, waitHot() delayed signalling compansates
for these changes. The estimation may fail, but
this should correct itself in the next 200 msec
signal.
> fn: agent slot improvements

- docs/developers/function-file.md
closes https://github.com/fnproject/cli/issues/145#issuecomment-359546714
> fixes header format in function file docs

- release.sh
> Nitfix: dropped a line during rebase :-(

- release.sh
I have no idea when those lines got dropped. Put 'em back.
> Actually build the final docker image before release!

- api/agent/stats.go
The "legacy" stats API (`/stats`), which is currently used by the UI tool, has a bug. The bug is that the returned data is simply a list of route stats, keyed by path. So this would not distinguish between two routes, in different apps, which had the same path. It would simply merge the stats for the two routes together, which would be extremely misleading.
```
{
"Queue": 0,
"Running": 10,
"Complete": 23,
"Failed": 10,
"FunctionStatsMap": {
"/hello-cold-async-a1": {
"Queue": 0,
"Running": 0,
"Complete": 0,
"Failed": 9
},
"/hello-cold-async-a2": {
"Queue": 0,
"Running": 4,
"Complete": 1,
"Failed": 0
},
...
```
(Full example [here](https://gist.github.com/nigeldeakin/662af33f366b539c0d855de7bc4c3847))
This PR fixes this bug by reorganising the data into two levels: app and then path. So it …
> Extend /stats API to handle two routes with the same path in different apps

- .circleci/config.yml
- Gopkg.lock
- Gopkg.toml
- README.md
- api/agent/agent.go
- api/agent/drivers/docker/docker.go
- api/agent/drivers/docker/docker_client.go
- api/agent/drivers/docker/docker_test.go
- api/agent/drivers/driver.go
- vendor/github.com/coreos/go-semver/.travis.yml
- vendor/github.com/coreos/go-semver/LICENSE
- vendor/github.com/coreos/go-semver/README.md
- vendor/github.com/coreos/go-semver/example.go
- vendor/github.com/coreos/go-semver/semver/semver.go
- vendor/github.com/coreos/go-semver/semver/semver_test.go
- vendor/github.com/coreos/go-semver/semver/sort.go
1) now required docker version is 17.06
2) enable circle ci latest docker install
3) docker driver & agent check minimum version before start
> fn: docker version checks

- api/agent/agent.go
- api/agent/slots.go
- api/agent/slots_test.go
these were just dangling off on the side, took some plumbing work but not so
bad
> plumb ctx for container removal spanno

- images/fn-test-utils/fn-test-utils.go
read/write a file on disk, alloc/leak memory.
> fn: more functionality into fn-test-utils

- images/fn-test-utils/fn-test-utils.go
Simulate partial output or invalid json/html in fn-test-utils.
> fn: fn-test-utils: partial output and invalid http or json

- api/server/runner_test.go
1) oom test
2) invalid http resp code test
3) check for error string contents in various error cases
> fn: test case additions

- api/agent/drivers/driver.go
- api/agent/drivers/driver_test.go
> support deeper / nesting of image names

- images/dind/build.sh
- images/dind/release.sh
1) use dind docker version instead of installed local docker
2) do not skip pre-release semver handling, eg. 17.12.0-ce
> fn: dind image version fixes

- api/agent/protocol/http.go
- api/agent/protocol/json.go
* http now buffers the entire request body from the container before copying
it to the response writer (and sets content length). this is a level of sad i
don't feel comfortable talking about but it is what it is.
* json protocol was buffering the entire body so there wasn't any reason for
us to try to write this directly to the container stdin manually, we needed to
add a bufio.Writer around it anyway it was making too many write(fd) syscalls
with the way it was. this is just easier overall and has the same performance
as http now in my tests, whereas previously this was 50% slower [than http].
* add buffer pool for http & json to share/use. json doesn't create a new
buffer every stinkin request. we need to plumb down content length so that we
can properly size the buffer for json, have …
> fixup json,http protocols

- api/agent/slots.go
- api/agent/slots_test.go
this somewhat minimally comes up in profiling, but it was an itch i needed to
scratch. this does 10x less allocations and is 3x faster (with 3x less bytes),
and they're the small painful kind of allocation. we're only reading these
strings so the uses of unsafe are fine (I think audit me).  the byte array
we're casting to a string at the end is also heap allocated and does 
escape. I only count 2 allocations, but there's 3 (`hash.Sum` and
`make([]string)`), using a pool of sha1 hash.Hash shaves 120 byte and an alloc
off so seems worth it (it's minimal). if we set a max size of config vals with
a constant we could avoid that allocation and we could probably find a
checksum package that doesn't use the `hash.Hash` that would speed things up a
little (no dynamic dispatch, doesn't allocate in …
> reduce allocs in getSlotQueueKey

- api/agent/drivers/docker/docker_client.go
Otherwise, retry function logs errors/timeouts, etc. but we do not know what operation is being performed.
> fn: add docker command info to retry when logging errors

- api/agent/drivers/docker/docker.go
Reed Allman <rdallman10@gmail.com>'s I/O error fix.
> fn: plumb up I/O errors from docker wait

- api/agent/agent.go
- api/agent/config.go
TODO: move all constants/tweaks in agent to agent config.
> fn: introduce agent config and minor ghostreader tweak

- api/agent/drivers/docker/docker_test.go
- api/agent/drivers/driver_test.go
- api/datastore/internal/datastoretest/test.go
- api/logs/testing/test.go
- api/server/middleware_test.go
- api/server/routes_test.go
- api/server/runner_async_test.go
- api/server/server_test.go
TODO: clean up fn-api-tests to use fn-test-utils.
> fn: favor fn-test-utils over hello (to be decommissioned)

- api/server/runner_test.go
- images/fn-test-utils/fn-test-utils.go
This is prep-work for more tests to come.
*) remove http response -1, this will break in go 1.10
*) add docker id & hostname to fn-test-utils (will be useful
to check/test which instance a request landed on.)
*) add container start/stop logs in fn-test-utils. To detect
if/how we miss logs during container start & end.
> fn: runner tests and test-utils enhancements

- api/agent/nodepool/grpc/grpc_pool.go
If a runner disconnect not gracefully it could happen that the
connection get stuck in connecting mode, this change verifies the state
of the connection before starting to execute a call, if the client
connection is not ready we fail fast to give a change to the next runner
(if any) to execute the call.
> Check runner connection before sending requests

- api/agent/agent.go
- api/server/runner_test.go
1) in theory it may be possible for an exited container to
requeue a slot, close this gap by always setting fatal error
for a slot if a container has exited.
2) when a client request times out or cancelled (client
disconnect, etc.) the slot should not be allowed to be
requeued and container should terminate to avoid accidental
mixing of previous response into next.
> fn: timeouts and container exits should stop slot queueing

- api/agent/agent.go
- api/agent/async.go
- api/agent/config.go
- api/agent/pure_runner.go
- api/agent/resource.go
- api/agent/resource_test.go
- api/server/runner_test.go
*) Moving constants in agent to agent config, which helps
with testing, tuning.
*) Added max total cpu & memory for testing & clamping max
mem & cpu usage if needed.
> fn: reorg agent config

- poolmanager/server/controlplane/vagrant_plugin/vagrant.go
Cleans up code to just make it refer to only vagrant
> Remove refs to vbox and just use vagrant

- api/server/server.go
*) switch to /proc/<pid>/cmdline due to /proc/<pid>/status
process name truncation.
*) Optional override with FN_PROCESS_COLLECTOR_LIST
> fn: add docker-containerd to prometheus processes

- api/datastore/sql/migratex/migrate.go
the error itself from up/down & dirty can be improved to show direction and
version information to help a user of the package determine where things went
wrong, which is useful when a series of migrations are run and the db error
itself is not clear about what went wrong exactly.
re: https://github.com/fnproject/fn/pull/641#issuecomment-374652245
> migratex: return more robust errors

- api/id/id.go
i bring great shame to my family
> fix id counter

- api/id/id.go
- api/id/id_test.go
another bone head fail here (mine). hopefully can leave this alone meow...
newID does not get inlined, but doesn't allocate to trigger any stack
expansion either. net perf hit on my laptop is 5ns, and we get a test out of
it. it will push a new stack, so it's not negligible overhead and we could
avoid it. we could keep the logic in both places just to have a test for it
separate instead of re-using the function in the hot path. up to us.
> fix machine id to 48 bits, add test

- api/agent/agent.go
- api/agent/doc.go
- api/agent/drivers/doc.go
- api/agent/drivers/docker/doc.go
- api/agent/drivers/mock/mocker.go
- api/agent/lb_agent.go
- api/agent/protocol/doc.go
Add some godoc comments for the api/agent package and some of its
subpackages.
> Godoc fixes

- api/agent/drivers/docker/docker_pool_test.go
> fn: experimental prefork tests should skip non Linux OSs

- api/agent/slots.go
There are alternative formulations of this, for instance see
https://www.reddit.com/r/golang/comments/5zctpf/unsafe_conversion_between_strings_and_byte_slices/
The problem manifested in the returned values from unsafeBytes occasionally
being broken. It's possible that by keeping a reference to the `a` parameter
alive, the original code would still work - however, this definitely seems like
a fix.
(A cast to `[]byte(a)` looks increasingly attractive, for all that it'll
perform small allocations and copies.)
> Bugfix: unsafeBytes slices were getting GCed

- api/agent/lb_agent.go
State trackers do not apply to LB agent.
> fn: lb_agent state trackers only apply to runners

- test/fn-api-tests/utils.go
*) removed unused cancel in api-test harness/server
*) removed hard coded port in getServerWithCancel along
with faulty health check code.
*) in SetupHarness() fixed code that skipped server start.
> fn: api and systems tests port cleanup

- api/agent/agent.go
- api/agent/call.go
- api/agent/protocol/cloudevent.go
- api/agent/protocol/factory.go
- api/agent/protocol/json.go
- api/agent/protocol/json_test.go
- api/models/call.go
- api/models/route.go
- docs/developers/ce-example.json
- docs/developers/cloudevents.md
- docs/developers/function-format.md
This adds CloudEvent format as I/O format. 
This now has support for ingestion of CloudEvents as input via HTTP as well as the function I/O format.
> CloudEvents I/O format support.

- README.md
> tutorials link

- api/agent/lb_agent_test.go
- api/runnerpool/ch_placer.go
- api/runnerpool/naive_placer.go
*) Naive is now a naive RR algorithm.
*) Both now checks for ctx/timeout in each attempt.
> fn: LB ch and naive fixes

- api/agent/pure_runner.go
> fn: pure-runner violates io Writer contract

- docs/fn-2.0/README.md
Some updates on triggers and FDK's.
> Updated cli section on triggers and FDK's.

- api/agent/pure_runner.go
- api/agent/runner_client.go
This should return a retriable error code 503.
> fn: pure-runner time out while waiting TryCall

- test/fn-api-tests/utils.go
- test/fn-system-tests/system_test.go
*) singleton style teardown for api tests
*) cancel content for system tests
> fn: shutdown improvements

- api/agent/resource.go
Non-Linux systems skip some of memory/cpu determination
code in resource tracker. But config settings to cap
these are used in tests, so they must not be ignored.
With this change, we apply these config settings even
on non-Linux systems.
Memory allocation code is also now same in non-Linux
systems, but default is raised to 2GB from 1.5GB.
> fn: MaxTotalCPU and MaxTotalMemory in non-Linux systems

- api/datastore/sql/migrations/15_alter_apps.go
- api/datastore/sql/sql.go
This allows for renaming apps in the future.
> ID should be primary key on apps model and name should be unique.

- api/server/server.go
https://github.com/fnproject/fn/pull/1058/files#r194913723
maybe i missed some context, but in general think this is the right thing to do
> should turn on views regardless of exporter

- api/common/logging.go
- api/datastore/sql/sql.go
> Mask DB password in logs

- docs/developers/function-timeouts.md
NA
- What I did
Fixed broken links in the docs
- How I did it
Updated the MD file
Click the links!
Fixed broken links in the docs
:-)
> Fixed broken links

- api/server/fns_delete.go
- api/server/fns_test.go
- api/server/trigger_delete.go
- docs/swagger_v2.yml
Fixes a couple of incorrect response codes (204 instead of 200), and replaces an occurrence of "route" with "function".
> Fixed up a couple of incorrect response codes

- docs/faq.md
> fn: add explanation of read-only disk and /tmp in faq/persistence.

- docs/operating/routes.md
quick typo in operating manual
> Fix verbs in docs

- README.md
Added a note on the section about using the shell script to set up the proxy environmental variables before running the script.  Also updated MacOS to macOS
- What I did
- How I did it
> Note on Shell script about proxy

- api/agent/call.go
- docs/developers/function-format.md
Similar to FN_MEMORY, we pass FN_TMPSIZE to function config.
> fn: applications should be aware of reserved writable space

- api/const.go
- api/server/call_logs.go
- api/server/defaultexts/defaultexts.go
- api/server/extension_points.go
- api/server/gin_middlewares.go
- api/server/middleware.go
- api/server/middleware_test.go
- api/server/route_listeners.go
- api/server/runner.go
- api/server/runner_test.go
- api/server/server.go
- api/server/server_options.go
- api/server/server_test.go
- api/server/stats.go
- examples/apps/blog/func.go
- examples/apps/hellos/func.go
- examples/extensions/main.go
- examples/inputs/func.go
- examples/middleware/main.go
- examples/tutorial/async/go/func.go
- examples/tutorial/hello/go/func.go
- examples/tutorial/hello/go/usingdeps/func.go
- examples/tutorial/logging/main.go
- fnext/api.go
- fnext/datastore.go
- fnext/listeners.go
- fnext/setup.go
- images/fn-test-utils/fn-test-utils.go
- images/hello/hello.go
- test/fn-system-tests/system_test.go
ongoing for #1064 - this fixes about 200 LOC that weren't lint compatible. there are 408 left at time of writing, so this will take a few sweeps. it will be easier to do these in piece meal fashion as some of the changes slightly break things over naming conventions that we should adhere to (are easy to fix in the service that imports this). since we're mostly not a shop of go folks, I think this will be immensely helpful to keep things a little more honest. these are kind of all robot-mandated changes and shouldn't require too much review, for the most part it's adding comments or making things lower cased so that they don't need comments
> Lint sprint

- api/models/annotations.go
- api/models/annotations_test.go
> String helper for annotations

- docs/README.md
- docs/developers/configs.md
- docs/faq.md
Didn't create one.
- What I did
Change links to func.file in 3 places:
1. docs/developers/configs.md
2. docs/README.md
3. docs/faq.md
- How I did it
Edited the affected files.
Verified fix on branch.
Fixlinks to func-file.md
**The Door**
> Fixlinks to func-file.md

- api/agent/pure_runner.go
Status calls should not directly use client
gRPC context deadlines/timeouts during Status
execution. Status should allow plenty of time
for the scheduler agent and docker to run and
emit useful error information.
Setting this timeout to 60 seconds, which should
surface disk I/O, docker, etc. issues.
> fn: Status gRPC call timeout handling

- api/agent/runner_client.go
> fn: add context into to logger passed to DialWithBackoff

- api/agent/agent.go
- api/agent/agent_test.go
- api/agent/call.go
- api/agent/config.go
- api/agent/lb_agent.go
- api/agent/resource.go
- test/fn-system-tests/system_test.go
#1138 should be able to rebase on this with relative ease (since the lines are identical)
attempting to simplify some stuff out of #1138 here
> make agent options/config pass lint checks

- api/server/server.go
In a customised server where runners get state via a customised data store  we want to be able to bypass the Hybrid API to reduce the API server footprint.
> Add server API to disable hybrid API on API servers

- api/server/gin_middlewares.go
> fn: add missing api response count in API metrics

- api/agent/call.go
- api/models/error.go
- api/server/runner_fninvoke.go
- api/server/runner_fninvoke_test.go
- api/server/server.go
A version of Fn invoke that works exactly like the trigger endpoint point.
> Adding Fn invoke endpoint that works just like triggers endpoint

- docs/operating/extending.md
> Updating extensions doc

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/fsouza/go-dockerclient/AUTHORS
- vendor/github.com/fsouza/go-dockerclient/Gopkg.toml
- vendor/github.com/fsouza/go-dockerclient/auth.go
- vendor/github.com/fsouza/go-dockerclient/auth_test.go
- vendor/github.com/fsouza/go-dockerclient/container.go
- vendor/github.com/fsouza/go-dockerclient/env.go
- vendor/github.com/fsouza/go-dockerclient/plugin.go
- vendor/github.com/fsouza/go-dockerclient/plugins_test.go
- vendor/github.com/fsouza/go-dockerclient/volume.go
- vendor/github.com/fsouza/go-dockerclient/volume_test.go
NA
- What I did
updates fsouza in order to get identityToken
- How I did it
dep ensure after changing Gopkg.toml rev for fsouza/go-dockerclient
ci pass
update fsouza deps
> Update fsouza in order to get identityToken

- api/agent/agent.go
Slot stats are too noisy. These should be (or shortly will be) in
metrics/stats/tracing.
> fn: slot metrics/stats should be in stats/metrics removing logging

- api/agent/agent.go
- docs/developers/fn-format.md
small updates to work from #1202 from yesterday, meant to put these on that... easy one.
> update docs with pro tips for fdk http stream people

- api/datastore/sql/migrations/21_drop_cols_path.go
- api/datastore/sql/sql.go
Fixes call migration for #1210
> Fix call migration

- api/agent/agent.go
- api/agent/call.go
- api/agent/resource.go
- api/agent/slots.go
- api/agent/slots_test.go
- api/agent/stats.go
New metrics for agent resource tracker: CpuUsed, CpuAvail,
MemUsed, MemAvail.
> fn: new agent resource tracker metrics

- api/agent/agent.go
- api/agent/config.go
- api/agent/drivers/docker/cookie.go
- api/agent/drivers/docker/docker.go
- api/agent/iofs.go
- api/agent/iofs_linux.go
- api/agent/iofs_notlinux.go
Looking to make this extensible for third parties wanting to instantiate custom agents.
> Add tmpfs IOFS

- api/agent/agent.go
> fn: add missing dequeue in agent Submit

- docs/swagger_v2.yml
> Add http-stream format to enum in swagger

- api/models/error.go
> fn: added http 429 in models Errors

- api/models/app.go
- api/server/apps_test.go
> help people figure out why their syslog url is wrong more better

- api/server/gin_middlewares.go
Adding a simple global path filter function to api views. This can
be set to a custom function to group path/url in API view tags.
For now, this is a simple one function. We could possibly have
a per Server or per Router filter, but I'm not sure if this is
necessary at this point.
> fn: api metrics custom path filter function

- api/agent/agent.go
> fn: disable keepalives for UDS http-stream client

- api/agent/drivers/docker/docker.go
- api/agent/drivers/docker/docker_client.go
Streaming docker events is useful as we can record/capture some
asynchronous containers events such as out-of-memory. For now,
we record these in opencensus/prometheus stats.
A sample section of prometheus metrics is:
```
fn_docker_events{event_action="attach",event_type="container"} 1
fn_docker_events{event_action="connect",event_type="network"} 1
fn_docker_events{event_action="create",event_type="container"} 1
fn_docker_events{event_action="destroy",event_type="container"} 1
fn_docker_events{event_action="die",event_type="container"} 1
fn_docker_events{event_action="disconnect",event_type="network"} 1
fn_docker_events{event_action="kill",event_type="container"} 1
fn_docker_events{event_action="oom",event_type="container"} 1
fn_docker_events{event_action="pause",event_type="container"} …
```
> fn: adding docker events to stats

- api/agent/agent.go
Make sure we unlock a blocked io.Copy()
> fn: fixup possible go-routine leak

- api/agent/runner_client.go
Adding http-status/fn-http-status details in runner finish
logger.
> fn: add details to runner finish logging

- api/agent/agent.go
- api/agent/resource.go
Previously evictor did not perform an eviction
if total cpu/mem of evictable containers was less
than requested cpu/mem. With this change, we
try to perform evictions based on actual needed cpu & mem
reported by resource tracker.
> fn: eviction resource correction

- api/agent/agent.go
> fn: blocking mode should not emit 503 if can't evict

- api/agent/agent.go
The channel is unnecessary and unreliable since exits
trigger I/O failure on UDS earlier than we detect
the exit.
> fn: Remove error channel for container exits

- images/fn-test-utils/fn-test-utils.go
These will be useful in future tests to simulate hung/slow
initialization, shutdown as well as UDS crash, etc.
> fn: adding pre/post sleep and UDS shutdown in fn-test-utils

- api/agent/agent.go
- api/agent/config.go
- api/agent/drivers/docker/docker.go
- api/agent/drivers/driver.go
> fn: remove tini option & env variable

- Makefile
- api/agent/agent.go
- api/agent/pure_runner.go
> fn: add comments

- api/agent/drivers/docker/docker_client.go
> fn: correct typo in docker command tag

- api/agent/agent.go
In runHot(), it's safer to use a separate channel between
monitoring go-routine and processing go-routine to handle
cancellations triggered by monitoring go-routine.
> fn: safer hand over between monitoring and main processing

- api/agent/lb_agent_test.go
- api/agent/static_pool.go
- api/agent/static_pool_test.go
- api/runnerpool/ch_placer.go
- api/runnerpool/naive_placer.go
- api/runnerpool/runner_pool.go
- test/fn-system-tests/exec_runner_status_test.go
- What I did
added context to runnerpool interface to use for logging additional information in LB
> added context for runnerpool interface

- api/agent/pure_runner.go
Added logging for status call failures.
> fn: status call failures should be logged

- build.ps1
https://github.com/fnproject/fn/issues/1342
- What I did
Add a curly brace and executed the script
- How I did it
Clone into windows and run build and run on powershell
Fix powershell build script
> Fix the powershell build script

- api/agent/resource.go
- api/agent/runner_client.go
- api/logs/s3/s3.go
- api/mqs/redis/redis.go
- api/server/server.go
edited logging variable format to fit same standard across all fn related repos
> edited logging variable format

- api/agent/agent_test.go
- api/agent/drivers/docker/cookie.go
- api/server/runner_fninvoke_test.go
- api/server/runner_httptrigger_test.go
- vendor/modules.txt
> fn: cherry pick 4xx errors from docker-pull and map rest to 502

- api/models/fn.go
> fn: remove unused constants

- api/agent/config.go
> fn: minor doc/comment update

- api/agent/drivers/docker/docker.go
ListContainers call which is asynchronously spawned
during docker driver start needs to have a reasonable
timeout and should be retried if timeout expires.
> fn: startup container cleanup timeout

- .circleci/config.yml
> Go upgrade for CVE-2019-6486

- api/agent/runner_client.go
During gRPC communication, previously we assumed that
Send(Try) message failure in TryExec(), can always
be retried. However, this is not robust as we cannot assume
no data was written to wire. With this change, before we
can conclude that the call can be retried, we also check
Unavailable error code.
> fn: retriable error handling in runner client

- test/fn-system-tests/.gitignore
> fn: add barrier_file to gitignore

- api/agent/pure_runner.go
- api/agent/stats.go
Switch all tags to tri-state to reduce confusion and add
network state.
> fn: status health checker stats update

- README.md
update the README to use the correct Twitter handle
> fixed twitter handle

- README.md
- Link to issue this resolves:
Demonstrates the best way to deploy an app.
- What I did
Added a step to create an app first.
- How I did it
Updated root README.md
Previous local testing.
Update quickstart to create app first
Akecheta makes a change
> Update quickstart to create app first

- README.md
been meaning to clean this page up a bit. here's a start.
- What I did: Edited the top-level readme
- How I did it: Voodoo magic
- How to verify it: Read it
- One line description for the changelog: Awesome changes
- One moving picture involving robots (not mandatory but encouraged): next time.
> Some readme cleanup

- api/agent/drivers/docker/docker_test.go
> fn: build fixup

- api/agent/agent.go
> fn: set headers before write header in http response

- api/datastore/sql/sql.go
> don't log db password

- api/agent/lb_agent.go
- api/agent/lb_agent_test.go
In the lbAgent at the moment it is not possible to add additional call
options other than the ones supplied to the GetCall.
This change adds a new WtihLBCallOptions functions to add that
capability to the lbAgent.
> Adding callOpts to lbAgent

- api/agent/agent_evict_test.go
- api/agent/agent_repo_test.go
Fake repository that returns 429 once for each http get. This
verifies our expectations of docker behavior when upstream
returns 429.
> fn: add repository pull tests

- api/agent/agent.go
- api/agent/config.go
- api/models/error.go
- api/server/runner_fninvoke_test.go
- api/server/runner_httptrigger_test.go
Allow limiting function response header size.
> fn: limit function header size if configured

- api/agent/pure_runner.go
- test/fn-system-tests/exec_runner_status_test.go
- test/fn-system-tests/system_test.go
- What I did
changed configuration handling by removing implementation and delegating it to consumer of pure_runner
- How I did it
provided an API to configure pure_runner and pass configuration handling code
system_test has a test to cover this
Improve runner configuration handling in pure_runner
> Improve runner configuration handling in pure_runner

- api/agent/agent.go
this adds https://golang.org/pkg/net/http/httptrace/ support to our opentracing spans using their built in goodies for it https://godoc.org/go.opencensus.io/plugin/ochttp for our uds requests from fn to function containers. these were pretty handy. learned some things: 1) the unfreeze latency actually shows up in latency inside of the function to wake up, not just in the unfreeze docker call, figured this out from when bytes are received in the function. 2) most of the time on my laptop anyway, even pipelining function invokes, I would not get an idle conn to the container and the uds client would have to make a new one, on my laptop this takes about 5ms, which is about 20-25% of the function exec time (with the freeze latency... without the freeze latency, my function runs in 1ms and …
> add httptrace to span, increase idle timeout

- release.sh
> push code with tags, not tag with tags

- release.sh
> have to explicitly state refspec to push it

- api/agent/iofs.go
When chmod fails, we should clean up the tmpdir.
> fn: fix minor leak in directoryIOFS

- api/server/server.go
Add option to disable profiler endpoints. The default is still to enable them, so this doesn't change anything for current usage.
Add option to disable profiler endpoints
> Add option to disable profiler endpoints

- api/server/server.go
This is useful when you only want to interact with the gRPC endpoints. By default this will still enable both the web and admin server, but it is possible to use the `WithWebEnabled` and `WithAdminEnabled` to disable either one.
> Add ability to disable web and admin server

- api/agent/agent.go
- api/agent/slots.go
> fn: provide update method for hot slot auther

- api/agent/agent.go
- api/agent/agent_test.go
- api/agent/slots.go
> fn: switch to extensions for slot queue auth token

- README.md
- Docs Issue: https://github.com/fnproject/docs/issues/54
- Tutorials Issue: https://github.com/fnproject/tutorials/issues/163
- What I did
- Added `brew update` before `brew install fn`
- How I did it
- Updated README
- View changes in Github
- Update MacOS installation via homebrew.
Robbie has a little of the home brew.
> Small update for homebrew install. Now consistent in all repos

- api/agent/runner_client.go
Add a new function, NewgRPCRunnerWithTimeout, that allows the caller to
define the grpc connection timeout.  Modify NewgRPCRunner to be
implemented in terms of NewgRPCRunnerWithTimeout, passing its existing
default timeout to the new function.
Addition of this function was necessary because the timeout here is
rather aggressive.  A test tool that leverages the existing
NewgRPCRunner was moved into an environment where its test target was in
a different region from the origin, which required a higher timeout to
cope with the test endpoint being physically farther away.
> Let runner clients specify a timeout at creation.

- api/agent/agent_test.go
> chore: unnecessary use of fmt.Sprintf
