fnproject/fn

- .circleci/config.yml
- Makefile
- api/agent/drivers/docker/docker_test.go
- api/agent/func_logger.go
- api/datastore/internal/datastoretest/test.go
- api/id/id.go
- api/models/route.go
- api/server/server.go
- examples/tutorial/hello/go/func.go
- fnlb/lb/ch.go
- fnlb/lb/proxy.go
- go-fmt.sh
- test.sh
go vet caught some nifty bugs. so fixed those here, and also made it so that
we vet everything from now on since the robots seem to do a better job of
vetting than we have managed to.
also adds gofmt check to circle. could move this to the test.sh script (didn't
want a script calling a script, because $reasons) and it's nice and isolated
in its own little land as it is. side note, changed the script so it runs in
100ms instead of 3s, i think find is a lot faster than go list.
attempted some minor cleanup of various scripts
> go vet yourself

- api/models/app.go
- api/models/route.go
they show up in the api and should at least be `{}` but I think omitting them is fine/better.
> omitempty these fields since they can be null

- api/server/server.go
This PR fixes an intermittent race condition which sometimes caused the following  panic at startup:
```
panic: interface conversion: opentracing.SpanContext is opentracing.noopSpanContext, not zipkintracer.SpanContext
goroutine 74 [running]:
github.com/fnproject/fn/vendor/github.com/openzipkin/zipkin-go-opentracing.(*tracerImpl).startSpanWithOptions()
/go/src/github.com/fnproject/fn/vendor/github.com/openzipkin/zipkin-go-opentracing/tracer.go:309  
github.com/fnproject/fn/vendor/github.com/openzipkin/zipkin-go-opentracing.(*tracerImpl).StartSpan()
/go/src/github.com/fnproject/fn/vendor/github.com/openzipkin/zipkin-go-opentracing/tracer.go:268  
github.com/fnproject/fn/api/server.FnTracer.StartSpan()
/go/src/github.com/fnproject/fn/api/server/fntracer.go:23 …
```
> Call setTracer() before Agent creation

- api/server/init.go
- api/server/server.go
Graceful shutdown should wait for Shutdown call instead of
ListenAndServe. This is because ListenAndServe returns
immediately upon Shutdown call.
> fn: graceful shutdown adjustments

- fnlb/lb/allgrouper.go
- fnlb/lb/allgrouper_test.go
- fnlb/lb/ch.go
- fnlb/lb/db.go
- fnlb/lb/proxy.go
- fnlb/lb/util.go
- fnlb/main.go
*) added healthy threshold (default: 1)
*) grouper now logs when servers switch between healthy/unhealthy state
*) moved DB code out of grouper
*) run health check immediately at start (don't wait until hcInterval)
*) optional shutdown timeout (default: 0) & mgmt port (default: 8081)
*) hot path List() in grouper now uses atomic ptr Load
*) consistent router: moved closure to a new function
*) bugfix: grouper is now using configured hcEndpoint for version checks
*) bugfix: version parsing from fn servers should not panic fnlb
*) bugfix: when servers removed from DB, stayed in healthy list
*) bugfix: if DB is down, health checker should not stop monitoring
*) basic new tests for grouper (add/rm/unhealthy/healthy) server
> fn: fnlb: enhancements and new grouper tests

- fnlb/release.sh
- release.sh
Changed:
* `fnproject/functions` to `fnproject/fn-server`
* `fnproject/fnlb` to `fnlb/fn-lb`
Keeps old image names for now too, but they are considered deprecated.
> Changed image names to be better and consistent

- api/agent/agent.go
- api/agent/async.go
- api/agent/drivers/docker/registry.go
- api/agent/resource.go
*) bugfix: fix nil ptr access in docker registry RoundTrip
*) move async and ram token related code into resource.go
> fn: move memory/token code into resource

- api/agent/drivers/docker/docker.go
- api/agent/drivers/docker/docker_client.go
before returning the cookie in the driver, wait for health checks
https://docs.docker.com/engine/reference/builder/#healthcheck if provided.
for images that don't have health checks, this will have no affect (an added
call to inspect container, for hot it's small potatoes).
this will be useful for containers so that they can pull large files or do
setup that takes a while before accepting tasks. since this is before start,
it won't run into the idle timeout. we could likely use these for hot
containers in general and check between runs or something, but didn't do that
here.
one nascient concern is that for hot if the containers never become healthy
I don't think we will ever kill them and the slot will 'leak'. this is true
for this and for other cases (pulling image) I think, we should …
> add docker health check waiter to start

- api/agent/agent.go
- api/agent/async.go
- api/models/error.go
- api/models/route.go
- api/server/error_response.go
- api/server/runner.go
- api/server/runner_test.go
*) Adding 503 with Retry-After header case if request failed
during waiting for slots.
*) Increased MaxMemory for routes to 100TB.
*) TODO: return 503 without Retry-After if the request can
never be met by this fn server.
closes #509
> fn: introducing 503 responses for out of capacity case

- examples/grafana/README.md
- examples/grafana/prometheus.yml
This PR Fixes #520. This changes the way that we tell Prometheus (running in a container) which host the Fn server is running on, and how we tell Grafana (also running in a container) which host Prometheus is running on. 
The fix is to replace `docker --addHost` with `docker --link`. This removes the need for a complicated shell expression that, it appears, doesn't work on MacOS (but worked just fine when I tested it on Ubuntu...)
> Fix for Prometheus/Grafana quickstart guide

- api/agent/agent.go
- api/agent/call.go
- api/agent/drivers/docker/docker.go
- api/agent/drivers/driver.go
- api/agent/drivers/driver_test.go
- api/datastore/sql/migrations/2_add_call_stats.down.sql
- api/datastore/sql/migrations/2_add_call_stats.up.sql
- api/datastore/sql/migrations/index.go
- api/datastore/sql/migrations/migrations.go
- api/datastore/sql/sql.go
- api/models/call.go
- docs/swagger.yml
this will add a histogram of up to 240 data points of call data, produced
every second, stored at the end of a call invocation in the db. the same
metrics are also still shipped to prometheus (prometheus has the
not-potentially-reduced version). for the API reference, see the updates to
the swagger spec, this is just added onto the get call endpoint.
this does not add any extra db calls and the field for stats in call is a json
blob, which is easily modified to add / omit future fields. this is just
tacked on to the call we're making to InsertCall, and expect this to add very
little overhead; we are bounding the set to be relatively small, planning to
clean out the db of calls periodically, functions will generally be short, and
the same code used at a previous firm did not cause a …
> add per call stats field as histogram

- api/agent/agent.go
- api/agent/stats.go
- examples/grafana/fn_grafana_dashboard.json
This PR extends the existing Prometheus metrics `fn_api_queued`, `fn_api_running`, `fn_api_completed` and `fn_api_failed` to add a label containing the name of the application. This makes it consistent with other Prometheus metrics, and is needed to support new features in the `ext_metrics` repo.
> Add appname to basic metrics

- api/agent/agent.go
- api/agent/agent_test.go
- api/agent/call.go
- api/datastore/internal/datastoretest/test.go
- api/datastore/sql/migrations/3_add_call_error.down.sql
- api/datastore/sql/migrations/3_add_call_error.up.sql
- api/datastore/sql/migrations/migrations.go
- api/datastore/sql/sql.go
- api/models/call.go
- docs/swagger.yml
- test.sh
closes #331
previously, for async this error was being masked completely even if it was
something useful like the image not existing. for sync, the error was returned
in the http request but now it's also being stored. this error itself can
cover a lot of landscape, it could be an error in getting a slot, pulling an
image, running a container, among other things. anyway, no longer being
masked. we can likely improve it in certain cases we run into in the future,
but it's open ended at the moment and not being masked like some errors in
sync http request returns (503 non-models.APIError) for now.
* tucks in callTrigger stuff to keep api clean
* adds swagger
* adds migration
* adds tests for datastore and agent to ensure behavior
> add error to call model

- docs/operating/kubernetes/README.md
- `kubectl -o jsonpath` removes need for user to have `jq` installed
- both `API_URL` env vars (k8s w/ LB and minikube) include `http://` prefix, so curl commands do not include `http://`
> use kubectl JSONPath

- api/server/extension_points.go
- api/server/routes_get.go
- api/server/server.go
- examples/extensions/README.md
- examples/extensions/main.go
This update extends the API extension mechanism to allow per-route API extensions. These use URLs of the following form:
```
http://localhost:8080/v1/apps/myapp/routes/myroute/custom5
```
The implementation is straightforward except for one thing. This was a runtime conflict between the extension handler and the existing handler in `api/server/server.go` for `/routes/*route`, since the latter uses a wildcard:
```
apps.GET("/routes/*route", s.handleRouteGet)
```
To avoid this I have changed the configuration of the existing handler to use `/routes/:route`, as follows:
```
apps.GET("/routes/:route", s.handleRouteGet)
```
However this means that the matched paths do not include a leading `/` character (which caused "route not found" errors) so I have changed `api/server/routes_get.go` to …
> Per route api extensions

- Dockerfile
- api/agent/agent.go
- api/agent/listeners.go
- api/server/app_listeners.go
- api/server/extension_points.go
- api/server/extensions.go
- api/server/gin_middlewares.go
- api/server/listeners.go
- api/server/middleware.go
- api/server/middleware_test.go
- api/server/runner.go
- api/server/server.go
- api/server/server_test.go
- docs/contributors/README.md
- docs/contributors/extensions.md
- docs/operating/extending.md
- examples/middleware/main.go
- fnext/api.go
- fnext/listeners.go
- fnext/middleware.go
- fnext/setup.go
- images/hello/hello.go
- main.go
* Adds root level middleware (was just API middleware)
* Adds control flow mechanism for middleware - [example](https://github.com/fnproject/fn/compare/root-middleware?expand=1#diff-370c8a94414d32d5ba9c77dedf9f318aR91)
* Moves extension interfaces to fnext package
> Middleware upgrade

- api/agent/agent.go
This PR modifies the tracing spans, and hence Prometheus metrics for the `agent_submit` operation, which essentially encompasses the execution of a cold or hot function. 
There are now three separate tracing spans (Prometheus metrics) with different baggage items (Prometheus labels) as follows:
* `agent_submit_route` - has the labels `fn_appname` and `fn_path` set
* `agent_submit_app` - has the label `fn_appname` set (but not `fn_path`)
* `agent_submit_global` - neither label set
These three separate metrics are required to support the queries needed by the new statistics API provided by the `ext-metrics` extension.
> More metrics

- README.md
When I followed these instructions on line 127 I got the docker error "Docker: Error response from daemon: could not get container for functions: No such container: functions." Looking at the containers set up by fn start it appeared that the name was fnserver.
Changing the link container  from functions to fnserver made it work for me.
> Changing to fnserver

- README.md
- docs/operating/selinux.md
Tiny little edit to remove the incorrect acronym "OEL" with the correct product name of Oracle Linux.
Resolves #583.
Signed-off-by: Avi Miller <avi.miller@oracle.com>
> [skip ci] Fix the name of Oracle Linux to the official product name.

- docs/operating/options.md
This really should of gone in as part of c5ec0cc41ecad26f443626e25f7248bc76e0c059 but better late than never.
> Added the API_CORS env var to the documented options

- examples/grafana/README.md
This corrects an error in the instructions for the Grafana example. The instructions told the user to configure a Grafana data source to connect to Prometheus using `http://prometheus:9090`, where `prometheus` is an alias configured using `--link`. However the instructions specified that the data source should use `direct` mode. This doesn't work, since the connection is then created from the browser, which doesn't know what `prometheus:9090` is. The instructions need to be changed to specify `proxy` mode, in which case the connection is created from Grafana, which knows about the `prometheus` alias.
> Update README.md for Grafana example

- api/server/server.go
Because it's not the URL of the runner, it's the URL of the api where you find the /runner endpoints.
> Hybrid mode: change runner api env var to FN_RUNNER_API_URL

- api/agent/agent.go
- api/agent/call.go
- api/agent/slots.go
*) moved slot management to its own file
*) slots are now implemented with LIFO semantics, this is important since we do
not want to round robin hot containers. Idle hot containers should timeout properly.
*) each slot queue now stores a few basic stats such as avg time a call spent in a given
state and number of running/launching containers, number of waiting calls in those states.
*) first metrics in these basic stats are discarded to avoid initial docker pull/start spikes.
*) agent now records/updates slot queue state and how much time a call stayed in that state.
*) waitHotSlot() replaces the previous wait 100 msec logic where it sends a msg to hot slot go routine launchHot() and waits for a slot
*) launchHot() is now a go routine for tracking containers in hot slots, it determines if …
> slot tracking improvements

- api/server/runner_test.go
- api/server/server_test.go
*) switching TestRouteRunnerTimeout to fn-test-utils to handle
both hot and cold.
*) in server_test added content-length handling as protocol http
does not create content-length if it is not present.
> fn: tests: adding hot container timeout and huge memory cases

- api/datastore/sql/sql.go
- api/models/app.go
- api/server/app_listeners.go
- api/server/apps_create.go
- api/server/apps_delete.go
- api/server/apps_get.go
- api/server/apps_list.go
- api/server/apps_update.go
- api/server/call_get.go
- api/server/call_list.go
- api/server/extension_points.go
- api/server/gin_middlewares.go
- api/server/hybrid.go
- api/server/middleware.go
- api/server/routes_create_update.go
- api/server/routes_delete.go
- api/server/routes_get.go
- api/server/routes_list.go
- api/server/runner_async_test.go
- api/server/server.go
- docs/developers/apps.md
- examples/apps/hellos/README.md
- fnext/context.go
- fnext/listeners.go
- fnext/middleware.go
- fnext/setup.go
This looks bigger than it is since there's a search and replace for `server.Database` -> `server.Database()`. 
Main gist is that it adds:
```
+	BeforeAppGet(ctx context.Context, appName string) error
+	AfterAppGet(ctx context.Context, app *models.App) error
+	BeforeAppsList(ctx context.Context, filter *models.AppFilter) error
+	AfterAppsList(ctx context.Context, apps []*models.App) error
```
And some changes to support this. 
Example where these changes are required is: https://github.com/treeder/fn-ext-auth/tree/master/simple
> Adds before/after app get/list. And some bug fixes/cleanup.

- api/server/apps_create.go
- api/server/apps_delete.go
- api/server/apps_get.go
- api/server/apps_list.go
- api/server/apps_update.go
- api/server/call_get.go
- api/server/call_list.go
- api/server/call_logs.go
- api/server/extension_points.go
- api/server/hybrid.go
- api/server/listeners.go
- api/server/prometheus_metrics.go
- api/server/routes_create_update.go
- api/server/routes_delete.go
- api/server/routes_get.go
- api/server/routes_list.go
- api/server/runner.go
- api/server/runner_async_test.go
- api/server/server.go
- api/server/stats.go
this patch has no behavior changes, changes are:
* server.Datastore() (uses in `api/server` only) -> server.datastore
* server.MQ -> server.mq
* server.LogDB -> server.logstore
* server.Agent -> server.agent
these were at a minimum not uniform. further, it's probably better to force
configuration through initialization in `server.New` to ensure thread safety
of referencing if someone does want to modify these as well as forcing things
into our initialization path and reducing the surface area of the Server
abstraction.
> unexport all data abstractions on Server

- api/agent/protocol/json_test.go
- api/datastore/internal/datastoretest/test.go
- api/datastore/mock.go
- api/datastore/sql/migrations/4_add_route_updated_at.down.sql
- api/datastore/sql/migrations/4_add_route_updated_at.up.sql
- api/datastore/sql/migrations/5_add_app_created_at.down.sql
- api/datastore/sql/migrations/5_add_app_created_at.up.sql
- api/datastore/sql/migrations/6_add_app_updated_at.down.sql
- api/datastore/sql/migrations/6_add_app_updated_at.up.sql
- api/datastore/sql/migrations/migrations.go
- api/datastore/sql/sql.go
- api/models/app.go
- api/models/config.go
- api/models/route.go
- api/server/apps_create.go
- api/server/apps_test.go
- api/server/routes_create_update.go
- api/server/routes_test.go
- docs/swagger.yml
- images/dind/build.sh
- images/error/build.sh
- images/fn-test-utils/build.sh
- test/fn-api-tests/routes_test.go
closes #367 
this finishes the time stamp saga for apps & routes, with created_at and updated_at on each one. should be pretty straight forward, there's some minor changes to tests / route init logic.
there are tests to ensure that these things are getting set.
> Timestamps on apps / routes

- api/server/server.go
- api/server/server_test.go
this should keep the old default behavior but allow users to pass in a
configured agent to configure the server themselves, without having to worry
about a russian agent being a british agent.
also closes any agent given to an api node.
closes #623
> allow user configured agent in full node

- api/datastore/datastore.go
- api/datastore/sql/sql.go
- api/datastore/sql/sql_test.go
- api/logs/log.go
- api/logs/log_test.go
- api/server/server.go
- api/server/server_options.go
- api/server/server_test.go
- test/fn-api-tests/utils.go
- implements retry func specifically for SQL datastore ping
- fmt fixes
- using sqlx.Db.PingContext instead of sqlx.Db.Ping
- propogate context to SQL datastore
> Use retry func while trying to ping SQL datastore

- .gitignore
- Makefile
- api_test.sh
- test/fn-api-tests/apps_test.go
- test/fn-api-tests/calls_test.go
- test/fn-api-tests/exec_test.go
- test/fn-api-tests/formats_test.go
- test/fn-api-tests/routes_api.go
- test/fn-api-tests/routes_test.go
- test/fn-api-tests/utils.go
Refactoring API tests to take less time
- sqlite: tests 15s, overall time: 1m
- mysql: tests 15s, overall time: 59s
All time that CI takes: pulling images
> Speed up API tests

- .gitignore
- Makefile
- api_test.sh
- helpers.sh
- images/swagger-alpine/Dockerfile
- test.sh
- test/fn-api-tests/utils.go
* use PG alpine
* use Minio alpine
* no official alpine distro for MySQL, uhhh :(
* install swagger tool instead of docker image
* use retry func to confirm that datastore is okay before running tests
> Use alpine images to make tests take less time

- .circleci/config.yml
`release.sh` does this upon release anyway, this is the last step in the
build. while nice to verify this, it does take 2 minutes on every branch
build, which is almost 1/3 of our build time now.
> remove arbitrary docker build in CI

- api/server/call_logs.go
- api/server/server.go
- clients/build.rb
- docs/swagger.yml
- test/fn-api-tests/exec_test.go
Fn API changed.
Swagger updated.
Certain API tests were disabled to make CI happy.
> Ship call logs to the user as text/plain instead of JSON

- .circleci/config.yml
this shaves 1 minute off of every build (~20%). we used to need 17.05 and had to install it ourselves, now we're provided 17.06, so our tests all work. I'm sure we'll run into needing to do this again in the future, but if we only have to do it periodically that'd be ok. i played with caching all of apt without much success, since docker is installed it sleeps 20s (could skirt this) but still took another 30s to stop old docker / install new one, this is 100% faster than that.
> skip docker installation in CI

- api/agent/stats.go
This PR adds a new Prometheus counter metric `fn_api_calls` which gives the number of function calls that have been made since the Fn server was started. 
As with the Prometheus metrics `fn_api_queued`, `fn_api_running`, `fn_api_completed` and `fn_api_failed` the labels `app` and `path` are set.
Note that the `/stats` API call has *not* been extended to return this metric since it is considered deprecated and will be removed at some point.
Note also that as with the Prometheus metrics `fn_api_queued`, `fn_api_running`, `fn_api_completed` and `fn_api_failed`, the Prometheus go client is called directly by the agent code. It is planned to change this in the future so that the agent code calls the open tracing API instead, but that will be a separate change.
This new metric is required by …
> Add calls metric

- api/agent/agent.go
- api/agent/slots.go
- api/agent/slots_test.go
*) new inactivity time out for hot queue, we previously kept hot queues in memory forever.
*) each hot queue now has a hot launcher to monitor and launch hot containers
*) consumers now create a consumer channel with startDequeuer() that can be cancelled via context
*) consumers now ping (signal) hot launcher every 200 msecs until they get a slot
*) tests for slot queue & mgr
> Slot mgr fixes

- docs/swagger.yml
we need to keep it like this until we move to swagger 3, so that we don't
break clients using old versions of fn and new clients.
see https://github.com/fnproject/cli/pull/128#issuecomment-355070594 for details.
related: https://github.com/fnproject/cli/pull/138
need to regen clients if we generated them w/ plain text version
> revert swagger to json for logs

- api/logs/s3/s3.go
> Logs should support specifying region when using S3-compatible object store 

- glide.yaml
- licenses.sh
this takes info from glide.lock, which covers all our external dependencies,
and then searches for a LICENSE in each of them. the good news is that it
covers all of our stuff right now, there are none without a license we can't
find. the bad news is, it's not very robust. this seemed to be a manual
process so this is markedly better.
removed 2 deps we had in glide.yaml that we aren't actually using, should go
away next update. one we just don't need to explicitly get (there are likely others)
to run: `./licenses.sh` -- we can likely generate a csv if that's preferable and put
it somewhere. we can also likely use this in the future to make sure we have a
handle on licenses in CI / make sure we don't use GPL / etc.
> add a license printing script 

- api/server/runner.go
- api/server/runner_test.go
- api/server/server.go
- docs/developers/apps.md
This fixes an issue where if the function call doesn't match a gin route, it would return a 404, even though the function ran fine. 
Also, while trying to debug this, I made some of the function executing methods return an error which cleans things up a bit (IMO), and allows callers to know if something went wrong.
> Fixes 404 responses from functions that go through NoRoute path.

- api/agent/call.go
- api/agent/protocol/factory.go
- api/agent/protocol/http.go
- api/agent/protocol/json_test.go
- api/server/runner_async_test.go
- api/server/runner_test.go
- images/fn-test-utils/Gopkg.lock
*) Updated fn-test-utils to latest fdk-go
*) Added hot-json to runner tests
*) Removed anon function in FromRequest which had
a side effect to set req.URL.Host. This is now more
explicit and eliminates some corresponding logic in
protocol http.
*) in gin, http request RequestURI is not set, removed
code that references this. (use Call.URL instead)
> fn: URL parsing updates to fix json request_url

- api/agent/agent_test.go
- api/agent/call.go
- docs/writing.md
Current:
```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=1cc0625aeae0
FN_PARAM_app=foo
FN_TYPE=sync
FN_METHOD=GET
FN_PARAM_route=/testfn
FN_HEADER_Accept_Encoding=gzip
FN_HEADER_User_Agent=Go-http-client/1.1
FN_PATH=/testfn
FN_FORMAT=default
FN_APP_NAME=foo
FN_REQUEST_URL=http://localhost:8080/r/foo/testfn
FN_HEADER_Content_Type=application/json
FN_MEMORY=128
FN_CALL_ID=01C3DB9X4Y47WG600000000000
HOME=/root
Body
```
The FN_PARAM_app/route are the only values that will ever show up since it's the only matching gin route possible. And they already exist in FN_APP_NAME and FN_PATH. 
cc @zootalures
> Removes FN_PARAM_xxx

- api/agent/agent.go
- api/agent/agent_test.go
- api/agent/call.go
- api/agent/protocol/http.go
- api/agent/protocol/json.go
- api/agent/slots.go
- api/models/call.go
- api/server/calls_test.go
- api/server/runner.go
- docs/function-format.md
- docs/writing.md
possible breakages:
* `FN_HEADER` on cold are no longer `s/-/_/` -- this is so that cold functions
can rebuild the headers as they were when they came in on the request (fdks,
specifically), there's no guarantee that a reversal `s/_/-/` is the original
header on the request.
* app and route config no longer `s/-/_/` -- it seemed really weird to rewrite
the users config vars on these. should just pass them exactly as is to env.
* headers no longer contain the environment vars (previously, base config; app
config, route config, `FN_PATH`, etc.), these are still available in the
environment.
this gets rid of a lot of the code around headers, specifically the stuff that
shoved everything into headers when constructing a call to begin with. now we
just store the headers separately and add a …
> make headers quasi-consistent

- docs/README.md
- docs/operating/private_registries.md
Fixes #35.
This introduces documentation based on the change in https://github.com/fnproject/cli/pull/131 to better support private registries.
Please let me know if this requires any more interlinking between documentation pages or if other pages need to be updated.
> Added documentation for private registries

- api/common/logging.go
- api/server/init.go
- api/server/server.go
- docs/operating/options.md
* FN_LOG_DEST can point to a remote logging place (papertrail, whatever)
* FN_LOG_PREFIX can add a prefix onto each log line sent to FN_LOG_DEST
default remains stderr with no prefix. users need this to send to various
logging backends, though it could be done operationally, this is somewhat
simpler.
we were doing some configuration stuff inside of init() for some of the global
things. even though they're global, it's nice to keep them all in the normal
server init path.
we have had strange issues with the tracing setup, I tested the last repro of
this repeatedly and didn't have any luck reproducing it, though maybe it comes
back.
> add FN_LOG_DEST for logs, fixup init

- api/agent/slots.go
Latency stats are not always read-time updated and
if calls are stuck in waiting state, isNewContainerNeeded()
needs to be a bit more aggresive if the wait queue grows.
> fn: hot container launcher adjustment

- api/agent/agent.go
this was getting bloated with various contexts and spans and stats
administrivia that obfuscated what was going on a lot. this makes some helper
methods to shove most of that stuff into, and simplifies the context handling
around getting a slot by moving it inside of slot acquisition code. also
removed most uses of `call.Model()` -- I'll kill this thing some day, but if a
reason is needed, then the overhead of dynamic dispatch is unnecessary, we're
inside of the implementee for the agent, we don't want to use the interface
methods inside of that.
the only behavior change is (should be) that the slot deadline no longer encloses call.Start(). right now this only changes a few fields and for async deletes the message. we could likely add additional padding like we do on call.End or limit it …
> clean up agent.Submit

- api/agent/agent.go
- api/agent/stats.go
This PR extends the set of basic metrics to add two more:
* `fn_timedout` -count of function calls that have not completed successfully because they timed out
* `fn_errors` - count of function calls that have not completed successfully because of an error (and because of a timeout)
This is in addition to the existing metrics
* `fn_failed` - count of function calls that have not completed successfully because of an error or timeout
* `fn_completed` - count of function calls that have completed successfully
* `fn_calls` - count of function calls that have made
So 
`calls` = `completed` + `failed`
`calls` = `completed + `errors` + `timedout`
These new metrics are required by the stats API: https://github.com/fnproject/fn/issues/514
I have extended the `ext-statsapi` tests to test these two …
> Add new Prom metrics fn_timeout and fn_errors

- images/dind/README.md
- images/dind/preentry.sh
This should probably be pushed back into the base image, and/or
upstream into dind's master.
In many k8s environments the host docker uses an overlay network
which'll take bytes away from the effective MTU of outer
containers; eg, vxlan needs 50 bytes, often leaving a 1450 MTU
on the container running dind and fn-api.
In such an arrangement, packets exceeding the smaller MTU may be
invisibly dropped as they travel across the dind's docker0
bridge. This mostly surfaces as a failure of functions to be able
to reliably talk to external services. (Note, the failure may be
intermittent depending on the profile of the resulting TCP
communication.)
A robust fix for this is to intercept the startup of the dind
dockerd and ensure that /etc/docker/daemon.json (currently
absent) contains the …
> Fix for MTU problems in some k8s environments

- api/agent/agent.go
- api/agent/async.go
- api/agent/resource.go
- api/agent/resource_test.go
- api/agent/slots.go
- api/agent/slots_test.go
*) Locked broadcast to avoid missed wake-ups.
*) Added go context with cancel to wait async resource. Although
today, the only case for cancellation is shutdown, this cleans
up agent shutdown a little bit.
> fn: cancellations in WaitAsyncResource

- api/agent/agent.go
- api/agent/async.go
- api/agent/resource.go
- api/agent/resource_test.go
- api/agent/slots.go
- api/agent/slots_test.go
*) Context argument does not wake up the waiters correctly upon
cancellation/timeout. Returning a cancel function clarifies
this and honors this contract better.
*) Avoid unnecessary broadcasts in slot and resource.
> fn: resource and slot cancel and broadcast improvements

- docs/developers/function-format.md
this behavior was recently cemented but was entirely omitted from the doc on
'how to write functions'
> add config placement info to docs

- api/agent/stats.go
This PR changes the name of the Prometheus metric `fn_timedout` to `fn_timedouts`, as proposed in https://github.com/fnproject/fn/issues/691. 
This metric tells you the number of timed out function calls, or the number of timeouts that have occurred.
> Change timedout to timeouts

- api/agent/agent_test.go
- api/agent/protocol/http.go
we were using a modified httputil.DumpRequest when there is a perfectly good
req.Write method hanging out in the stdlib, that even does the chunked thing
that a few people ran into if they don't provide a content length:
https://golang.org/pkg/net/http/#Request.Write -- so we shouldn't run into
that issue again. I hit this in testing and it was not very fun to debug, so
added a test that repro'd it on master and fixes it here. of course, adding a
content length works too. tested this and it appears to work pretty well, also
cleaned up the control flow a little bit in http protocol.
> fix the http protocol dumper

- api/agent/agent.go
- api/agent/stats.go
- examples/grafana/fn_grafana_dashboard.json
Added server busy / 503 stats and updated grafana dashboard:
> fn: added server too busy stats

- api/agent/agent.go
- api/agent/agent_test.go
- api/agent/async.go
- api/agent/call.go
- api/agent/resource.go
- api/agent/resource_test.go
* add root spans to async calls (oops) so we can see the span started in async land
* there were a few methods which had multiple contexts which existed in the same
scope (this doesn't end well, usually), flattened those out.
* loop bound context cancels now rely on defer (also was brittle)
* runHot had a lot of ctx shuffling, flattened that.
* added some additional spans in certain paths for added granularity
* linked up the hot launcher / run hot / wait hot to _a_ root span, the first
2 are follows from spans, but at least we can see the source of these and also
can see containers launched over a hot launcher's lifetime
I left TODO around the FollowsFrom because OpenCensus doesn't, at least at the
moment, appear to have any idea of FollowsFrom and it was an extra OpenTracing
method (we …
> additional ctx spans / maid service

- api/agent/agent.go
- api/agent/call.go
- api/agent/slots.go
- api/agent/slots_test.go
- api/agent/state_trackers.go
- api/agent/stats.go
- api/common/metrics.go
*) in stats.go no need to lock span log (aka common/metrics.go calls)
*) tracker code to simplify agent side and also track request vs container states.
*) slots code a bit clearer since 'waiters' is actually queued requests, versus 'starter' means starting containers.
*) for cold cookie run moved into prepCold() as this is part of container spawn/start phase as std IO is tied up to the container, with this we consider waiting on 'waiter' channel period is the 'execution' phase. This is not entirely true, but a close enough approximation.
*) container states get logged in spans as histograms (for time), and gauge (for counts)
> fn: better slot/container/request state tracking

- api/agent/agent.go
- api/agent/agent_test.go
- api/agent/call.go
- api/agent/protocol/factory.go
- api/agent/protocol/http.go
- api/agent/protocol/json.go
- api/agent/protocol/json_test.go
- docs/developers/function-format.md
Closes #662.
_This change will require FDKs which handle the `json` function format to be updated._
This change moves some Fn-specific fields around in the JSON protocol structure, thus improving the handling of Fn-specific fields that would otherwise end up in FN-prefixed headers. The rationale for this is in #662.
Fn-specific stuff (Call ID, request url, etc) that used to be stored in the headers of the `models.Call` is now instead added by the protocol dispatchers at the right time, so that the model reflects what the user has originally provided. The HTTP protocol dispatcher still creates Fn-prefixed headers, because that's the only way it can pass information to the function, but the JSON protocol can provide the information directly in JSON fields.
> Hot protocols improvements (for 662)

- .circleci/config.yml
- Dockerfile
- Makefile
- changed-since-last.sh
- images/dind/build.sh
- images/dind/release.sh
- release.sh
This needs a bit of an eyeball.
We check to see which bits of the tree have changed (this is a broad-grained test) before
forcing rebuilds of any dependencies (DIND in this case).
When it comes to releasing, we only release bits that've changed. Bump tags and versions
in code where necessary.
The fnserver release is basically unchanged; fnlb and DIND modified to work around it.
(I've added a handful of relevant reviewers as this is a bit fiddly.)
> Selective releasing

- api/datastore/internal/datastoretest/test.go
- api/datastore/internal/datastoreutil/validator.go
- api/models/app.go
- api/models/error.go
- api/server/apps_create.go
- api/server/routes_create_update.go
push validate/defaults into datastore
we weren't setting a timestamp in route insert when we needed to create an app
there. that whole thing isn't atomic, but this fixes the timestamp issue.
closes #738
seems like we should do similar with the FireBeforeX stuff too.
also:
* app name validation was buggy, an upper cased letter failed. now it doesn't.
uses unicode now.
* removes duplicate errors for datastore and models validation that were used
interchangably but weren't.
> Fix default setting

- api/agent/drivers/docker/docker.go
closes #317
we could fiddle with this, but we need to at least bound these. this
accomplishes that. 1m is picked since that's our default max log size for the
time being per call, it also takes a little time to generate that many bytes
through logs, typically (i.e. without trying to). I tested with 0, which
spiked the i/o rate on my machine because it's constantly deleting the json
log file. I also tested with 1k and it was similar (for a task that generated
about 1k in logs quickly) -- in testing, this halved my throughput, whereas
using 1m did not change the throughput at all. trying the 'none' driver and
'syslog' driver weren't great, 'none' turns off all stderr and 'syslog' blocks
every log line (boo). anyway, this option seems to have no effect on the
output we get in 'attach', which …
> limit log size in containers

- go-fmt.sh
Apparently GNU find lets you omit the directory but BSD find does not.
> Trivial fix to get 'make test' working on Mac

- api/agent/agent.go
- api/agent/slots.go
- api/agent/slots_test.go
- docs/operating/options.md
With this change, now we are allocating the timers
when the container starts and managing them via
stop/clear as needed, which should not only be more
efficient, but also easier to follow.
For example, previously, if eject time out was
set to 10 secs, this could have delayed idle timeout
up to 10 secs as well. It is also not necessary to do
any math for elapsed time.
> fn: hot container timer improvements

- api/agent/protocol/http.go
- api/agent/protocol/json.go
- api/server/runner_test.go
this was being thrown into the fn server logs but it's relatively easy to get
this to crop up if a function user forgets that they left a `println` laying
around that gets written to stdout, it garbles the http (or json, in its case)
output and they just see 'internal server error'. for certain clients i could
see that we really do want to keep this as 'internal server error' but for
things like e.g. docker image not authorized we're showing that in the
response, so this seems apt.
json likely needs the same treatment, will file a bug.
as always, my error messages are rarely helpful enough, help me please :)
closes #355
> return bad function http resp error

- api/agent/drivers/docker/docker_client.go
- api/server/runner_test.go
previously we would retry infinitely up to the context with some backoff in
between. for hot functions, since we don't set any dead line on pulling or
creating the container, this means it would retry forever without making any
progress if e.g. the registry is inaccessable or any other temporary error
that isn't actually temporary.  this adds a hard cap of 10 retries, which
gives approximately 13s if the ops take no time, still respecting the context
deadline enclosed.
the case where this was coming up is now tested for and was otherwise
confusing for users to debug, now it spits out an ECONNREFUSED with the
address of the registry, which should help users debug without having to poke
around fn logs (though I don't like this as an excuse, not all users will be
operators at some point in …
> cap docker retries to fixed number

- api/agent/drivers/docker/docker.go
we have been getting these from attach all this time and never needed these
anyway.
I ran cpu profiles of dockerd and this was 90% of docker cpu usage (json
logs). woot. this will reduce i/o quite a bit, and we don't have to worry
about them taking up any disk space either.
from tests i get about 50% speedup with these off. the hunt continues...
> disable fail whale logs

- api/server/init.go
- api/server/server.go
- images/dind/preentry.sh
1) in dind, prevent SIGINT reaching to dockerd. This kills
docker and prevents shutdown as fn server is trying to stop.
2) as init process, always reap child processes.
> fn: dind SIGINT and SIGCHLD changes

- api/agent/protocol/http.go
- api/agent/protocol/json.go
- api/server/profile.go
- api/server/server.go
i would split this commit in two if i were a good dev.
the pprof stuff is really useful and this only samples when called. this is
pretty standard go service stuff. expvar is cool, too.
the additional spannos have turned up some interesting tid bits... gonna slide
em in
> add pprof endpoints, additional spans

- docs/faq.md
The common mistake. `premise` means something else.
> `Premises` not `premise`

- test/fn-api-tests/exec_test.go
- test/fn-api-tests/utils.go
a lot of the logging tests use async calls which was flaky with timings. there
are a couple left that use async, that we need to test, but this reduces the
probability of the flaky tests flaking to 2/5 instead of 5/5.
the behaviors we are testing here we should not be testing through the api,
for this exact reason, we can test a ton of this in the agent itself and not
have to rely on timings. not taking that here, but this fixes circle ci
flaking out for a few days.
> use sync call for some api tests

- docs/swagger.yml
(#626) the Version is unused in the swagger.  Remove that
item from the definitions.
> removed unused item in swagger (#626)

- api/server/profile.go
expvar package exports Handler which can be directly used instead of copying the expvarHandler function.
> Remove replicated expvar handler

- api/server/app_listeners.go
- api/server/apps_create.go
- api/server/apps_delete.go
- api/server/apps_get.go
- api/server/apps_list.go
- api/server/apps_update.go
- api/server/routes_create_update.go
- api/server/server.go
- fnext/datastore.go
- fnext/listeners.go
fnext.NewDatastore returns a datastore that wraps the appropriate methods for
AppListener in a Datastore implementation. this is more future proof than
needing to wrap every call of GetApp/UpdateApp/etc with the listeners, there
are a few places where this can happen and it seems like the AppListener
behavior is supposed to wrap the datastore, not just the front end methods
surrounding CRUD ops on an app. the hairy case that came up was when fiddling
with the create/update route business.
this changes the FireBeforeApp* ops to be an AppListener implementation itself
rather than having the Server itself expose certain methods to fire off the
app listeners, now they're on the datastore itself, which the server can
return the instance of.
small change to BeforeAppDelete/AfterAppDelete -- we …
> push down app listeners to a datastore

- api/agent/slots.go
while escape analysis didn't lie that the bytes underlying this string escaped
to the heap, the reference to them died and led to us getting an undefined
byte array underlying the string.
sadly, this makes 4 allocs here (still down from 31), but only adds 100ns per
op. I still don't get why 'buf' and 'byts' escape to the heap, blaming faulty
escape analysis code. we could reduce one of them i guess, the hash sum
though will still escape.
this one is kind of impossible to write a test for.
found this from doing benchmarking stuff and was getting weird behavior at the
end of runs where calls didn't find a slot, ran bisect on a known-good commit
from a couple weeks ago and found that it was this. voila. this could explain
the variance from the slack dude's benchmarks, too. anyway, confirmed …
> fix undefined string slot key

- api/id/id.go
- api/id/id_test.go
... I was curious, may as well keep them
not bad, mostly `time.Now()` and the atomic add on high core machines might make this worse, anyway it's pretty good:
```
✗: go test -bench . -benchmem
goos: linux
goarch: amd64
pkg: github.com/fnproject/fn/api/id
BenchmarkGen-2                  20000000                73.7 ns/op             0 B/op          0 allocs/op
BenchmarkMarshalText-2          30000000                47.5 ns/op            32 B/op          1 allocs/op
BenchmarkUnmarshalText-2        100000000               17.6 ns/op             0 B/op          0 allocs/op
PASS
```
> add benchmarks for ids

- api/agent/agent.go
- api/agent/config.go
- api/agent/drivers/docker/docker.go
- api/agent/drivers/docker/docker_test.go
- api/agent/drivers/driver.go
- api/agent/drivers/mock/mocker.go
- api/agent/protocol/factory.go
- api/agent/protocol/http.go
- api/agent/protocol/json.go
- api/common/io_utils.go
- api/server/runner_test.go
- images/fn-test-utils/fn-test-utils.go
*) I/O protocol parse issues should shutdown the container as the container
goes to inconsistent state between calls. (eg. next call may receive previous
calls left overs.)
*) Move ghost read/write code into io_utils in common.
*) Clean unused error from docker Wait()
*) We can catch one case in JSON, if there's remaining unparsed data in
decoder buffer, we can shut the container
*) stdout/stderr when container is not handling a request are now blocked if freezer is also enabled.
*) if a fatal err is set for slot, we do not requeue it and proceed to shutdown
*) added a test function for a few cases with freezer strict behavior
> fn: I/O related improvements

- docs/developers/function-format.md
http://json.org/ says: `Whitespace can be inserted between any pair of tokens. Excepting a few encoding details, that completely describes the language.`
we do not explicitly need the whitespace between objects in our json, it's entirely optional and soon we will even support it (#830)!
> json format __definition__ omit whitespace between objects

- api/agent/lb_agent.go
- api/agent/nodepool/grpc/grpc_pool.go
- api/agent/pure_runner.go
- test/fn-system-tests/exec_test.go
Add a basic concurrency test for the dataplane system tests.
Also fix a minor issue with capacity accounting, discovered with tests, and remove some spurious logging.
> Add a basic concurrency test for the dataplane system tests

- api/agent/nodepool/grpc/grpc_pool.go
- grpcutil/dial.go
- poolmanager/client.go
This change add the option to set a timeout for the dialer used in
making gRPC connection, with that we remove the check on the state of
the connections and therefore remove any potential race conditions.
> Add a timeout to the net dialer

- api/datastore/sql/migratex/migrate.go
- api/datastore/sql/migratex/migrate_test.go
code is feature complete in the general sense, with minor TODO left.
this is just a patch with 'migratex' and does not use it for fn's migrations
yet, would like to get feedback prior to doing that.
presenting:
A migration library loosely based on pressly/goose and mattes/migrate design,
that does migrations across a smattering of sql databases by only accepting a
`*sqlx.DB`.
why?
* goose didn't support kindly allowing us to rebind transactions based on a
given db to various dialects or offer oracle support
* goose didn't support locking the db (maybe not needed with tx? it's late..
we may want to lock the whole db eventually?)
* goose requires us to do semi-complex migration to it from mattes/migrate
* mattes has stepped down as migrate maintainer and the project is in flux
* …
> phase 1 sqlx migrator

- api/agent/pure_runner.go
- api/server/server.go
- test/fn-system-tests/system_test.go
**PATCH 1/2 - blocks #849** 
This makes PureRunner a type of Agent and moves the grpc server initialization into the creation function.
This allows us to avoid having to create and start the grpc server in server.go, which was a bit of a smelly leakage from the PureRunner abstraction.
> Make PureRunner an Agent so that it encapsulates its grpc server

- api/server/server.go
the prometheus client we're using has a nice collector for process metrics and
for go metrics. these are things we are very interested in operationally and
recently the benevolent team at opencensus made this possible again, so this
hooks it up for us with added dockerd sugar.
nannying the dockerd we're using should be super useful since that thing likes
to get carried away, it'll be nice to differentiate memory/cpu usage between
dockerd  / the host / fn. this will basically only work in a 'dind'
environment, or on a linux host that is running fn outside of docker that is
configured with the permissions to be able to check this.  otherwise, it will
simply fail silently. we also probably want disk i/o and net i/o information for that
as well, or at least it would be interesting to …
> fn, dockerd pid collector & go collector metrics 

- README.md
Changed from fnproject.com/tutorials to fnproject.io/tutorials
The current one doesn't work so correcting the link. The current version of tutorials landing page at fnproject.io/tutorials is better than an error. :-)
> Updated Tutorials link

- Makefile
This speeded up tests before go 1.10 improvements, but
also clashed with fn cli tool, which gets installed as 'fn'.
> fn: remove pre go 1.10 optimization of build install

- api/agent/agent.go
- api/agent/config.go
- api/agent/drivers/docker/docker.go
- api/agent/drivers/docker/docker_test.go
- api/agent/drivers/driver.go
Added env FN_MAX_FS_SIZE_MB, which if defined and non-zero
is passed to docker as storage opt size. We do not validate
if this option is supported by docker currently. This is
because it's difficult to actually validate this since it
not only depends on storage driver and its backing filesystem,
but also the mount options used to mount that fs.
> fn: add storage opt size support

- api/models/runner_pool.go
- api/server/server.go
- fnext/setup.go
This PR provides a common extension point and abstractions for running fn in load-balanced mode. A runner pool encapsulates a group of runners that are available to service a particular fn call. A runner implements a simple calling contract that allows the routing/lb layer to retry requests on other runners in case it is not available.
Note: This is the first of a series of independent patches for extracting node pool manager as a custom extension.
> Adds extension points for runner pools in load-balanced mode (Patch 1/2)

- docs/developers/packaging.md
Minor fix to a bug reported by an end user--corrected the relative path to the main CLI README.md file
> Fix to broken CLI link.

- api/agent/agent.go
- api/agent/lb_agent.go
- api/agent/pure_runner.go
- api/server/server.go
- test/fn-system-tests/system_test.go
This change hides the details of delegated agent creations for the LB and the Pure Runner agents. 
This allows us to disable the docker driver for the LB agent, and hide that fact from the code that creates the LB agent. After all, nobody needs to know that the LB and the Pure Runner create a delegated agent. This brings LBAgent and PureRunner in line with other agent creation functions, as they will only take a DataAccess instead of requiring a user to create a delegated agent.
> Hide details of delegated agents for PR and LB, to disable docker for LB

- api/agent/call.go
- api/models/call.go
Another alternative to #878 (and #879)
This allows us to merge the Annotations from app and route (which are the useful information which is missing in Call) into the models.Call. The field is ephemeral like Config so it should not be persisted and should not cause issues.
> Expose route and app models to RunnerCall for extensions (alternative 2)

- api/agent/call.go
Incorporates @treeder's optimization from #880
> Create an Annotation map of the right size to avoid resizing

- .circleci/config.yml
- Gopkg.lock
- Makefile
- api/agent/agent.go
- api/agent/config.go
- api/agent/drivers/docker/docker.go
- api/agent/drivers/docker/docker_client.go
- api/agent/drivers/docker/docker_pool.go
- api/agent/drivers/docker/docker_pool_test.go
- api/agent/drivers/driver.go
- api/agent/drivers/mock/mocker.go
- api/agent/resource.go
- vendor/golang.org/x/time/AUTHORS
- vendor/golang.org/x/time/CONTRIBUTING.md
- vendor/golang.org/x/time/CONTRIBUTORS
- vendor/golang.org/x/time/LICENSE
- vendor/golang.org/x/time/PATENTS
- vendor/golang.org/x/time/README.md
- vendor/golang.org/x/time/rate/rate.go
- vendor/golang.org/x/time/rate/rate_go16.go
- vendor/golang.org/x/time/rate/rate_go17.go
- vendor/golang.org/x/time/rate/rate_test.go
For docker containers, it's possible to provide a new container with an existing namespace using "container:name" format. For example, for pass-in an existing network namespace to a new container:
```
docker run --name foo busybox sleep 600
docker run --name bar --network "container:foo" busybox echo hello
```
Which runs "bar" but using "foo"s network and user namespace.
This PR introduces a pool of asleep (dummy) containers that merely serve as a cache for network and user namespaces, similar to the 'foo' container in the example above.
This results in significant speed up in cold containers as well as burst (ramp up) handling of hot containers.
> fn: pre-fork pool for namespace/network speedup

- api/server/route_listeners.go
- api/server/server.go
- fnext/datastore.go
- fnext/listeners.go
The major need in this change that we allow developers to hook into the apps API and somehow calls API, however, the major resource (at this moment) - routes is still out of control from the extension developers.
This PR introduces similar API to apps listener, but for the routes.
Note: this might change to the triggers listeners once we split functions out of the routes.
> API extensions: Route listerens

- Gopkg.lock
- Gopkg.toml
0.4.0 is too low, no prometheus registry specification.
0.6.0 jaeger is broken. filing ticket w/ them.
closes #886
> dep: lock opencensus to commit

- api/agent/lb_agent_test.go
- api/agent/runner_client.go
- api/agent/static_pool.go
- api/agent/static_pool_test.go
- api/runnerpool/runner_pool.go
- api/server/server.go
- grpcutil/dial.go
In order to support TLS certificates with different Common Names, we need to extend the grpc utilities and the way we create runners.
> support runner TLS certificates with specified certificate Common Names

- Makefile
I noticed that the Makefile rule to build protobuf files was listing a
non-existent file and that the protobuf files were not getting rebuilt
during builds.
> Make sure to rebuild protobuf files during build

- api/agent/pure_runner.go
pureRunner is a not exported struct and it was set as a return value for
few exported methods, in this change we return Agent which is the
interface implemented by pureRunner to avoid to leak an unexported type.
> Returning Agent on exported func for pureRunner

- api/mqs/bolt.go
the bolt mq file should only be used for local dev and isn't necessarily
sensitive, don't think 0655 restriction was necessary and the data isn't
likely all that sensitive anyway.
see https://github.com/fnproject/fn/issues/404#issuecomment-377570626
closes #779
> loosen perms on bolt mq

- README.md
- api/agent/config.go
Oracle Linux 7.4 backported versions still having issues
with freezing/terminating containers. 17.10.0-ce seems like
a resonable lowest common denominator.
> fn: update minimum docker version required.

- api/agent/agent.go
- api/agent/config.go
- api/server/runner_test.go
call.End() performs several tasks in sequence; insert call,
insert log, (todo) remove mq entry, fireAfterCall callback, etc.
These currently add up to the request latency as return
from agent.Submit() is blocked on these. We also haven't been
able to apply any timeouts on these operations since they are
handled during request processing and it is hard to come up
with a strategy for it. Also the error cases
(couldn't insert call or log) are not propagated to the caller.
With this change, call.End() handling becomes asynchronous where
we perform these tasks after the request is done. This improves
latency and we no longer have to block the call on these operations.
The changes will also free up the agent slot token more quickly
and now we are no longer tied to hiccups in call.End().
Now, a …
> fn: perform call.End() after request is processed

- api/agent/agent.go
- api/agent/config.go
- api/agent/drivers/docker/docker.go
- api/agent/drivers/docker/docker_client.go
- api/agent/drivers/docker/docker_pool.go
- api/agent/drivers/docker/docker_pool_test.go
- api/agent/drivers/driver.go
*) Rework the control loop for the containers, where now we have two states: initializing and ready. This allows us to avoid expensive & unnecessary operations for backfill/recycle phases.
*) A recycle option which discards each pool item after use.
*) Network list option to provide a list of docker bridges to spread the pool into. Each docker bridge has a linux limitation of 1023 containers, so using this list, we can exceed that limit easily.
TODO: Recycle performs poorly in cold-containers as it runs out of pool items over time. This causes churn and increases system load significantly. Need to run/tune this recycle mode for hot containers and re-evaluate.
> Experimental Pre-fork Pool: Recycle net ns

- api/datastore/sql/sql.go
- api_test.sh
- helpers.sh
- system_test.sh
Setting this to high (60) in api and system tests.
> fn: datastore dial retry should be configurable

- api/agent/agent.go
- api/agent/agent_test.go
- api/agent/lb_agent.go
- test/fn-api-tests/exec_test.go
*) This simplifies submit() function but moves the burden
of retriable-versus-committed request handling and slot.Close()
responsibility to handleCallEnd().
*) handleCallEnd() related test fixes.
> fn: handleCallEnd and submit improvements

- api/agent/pure_runner.go
- test/fn-system-tests/system_test.go
*) Moved blocking I/O operations into their own go-routines.
*) gRPC send/receive is now performed via a dedicated go-routine for each direction. Blocking
semantics are now using channels, which can we unblocked via shutdown or gRPC context timeout.
> fn: pure runner concurrency fixes

- api/agent/lb_agent_test.go
Time.Sleep() blocking fixes in placers (naive and ch) improves
some of the timing in processing, therefore reducing the max
calls settings in mock runner pool.
> fn: lb_agent_test tweak

- .circleci/config.yml
With docker 18.04 the behaviour of a documented interface has changed from 18.03 -
to wit, you need to use a specific noninteractive mode of `docker login` to avoid
being prompted about insecure credential storage.
> Fix docker login syntax

- api/agent/agent.go
- api/agent/agent_test.go
- api/agent/call.go
- api/agent/func_logger.go
- api/agent/lb_agent.go
- api/agent/lb_agent_test.go
- api/agent/listeners.go
- api/agent/pure_runner.go
- api/runnerpool/ch_placer.go
- api/runnerpool/naive_placer.go
- api/runnerpool/runner_pool.go
- api/server/runner.go
lbagent and agent code is too dependent. This causes
any changed in agent to break lbagent. In reality, for
LB there should be no delegated agent. Splitting these
two will cause some code duplication, but it reduces
dependency and complexity (eg. agent without docker)
> fn: reduce lbagent and agent dependency

- api/common/ctx.go
- api_test.sh
- system_test.sh
- test.sh
Fix missing values in context created with common.BackgroundContext by using delegation to previous context (only for Value()).
Fixes #949 .
> Fix missing values in context created with common.BackgroundContext

- test/fn-system-tests/exec_test.go
In the case the function execution fails the output returned is empty, an
empty output satisfies the "string.Contanis()" check as an empty string
is always contained in any string.
The change adds a check on the length of the actual output.
> Fix assert check in system tests

- api/agent/agent.go
- api/agent/config.go
- api/agent/resource.go
- api/agent/resource_test.go
- api/agent/slots.go
- api/server/runner_test.go
For some types of errors, we might want to notify
the actual caller if the error is directly 1-1 tied
to that request. If hotLauncher is triggered with
signaller, then here we send a back communication
error notification channel. This is passed to
checkLaunch to send back synchronous responses
to the caller that initiated this hot container
launch.
This is useful if we want to run the agent in
quick fail mode, where instead of waiting for
CPU/Mem to become available, we prefer to fail
quick in order not to hold up the caller.
To support this, non-blocking resource tracker
option/functions are now available.
The solution is not perfect as signaller channels
may be lost and it might take additional signal attempts
for that call (each costs 200msec) to get this response.
> fn: non-blocking resource tracker and notification

- api/server/middleware.go
- api/server/middleware_test.go
When we chain middlewares, the last middleware does not use the request passed by the preceding middleware. If the preceding middleware read httpRequest.Body and set a new io.ReadCloser to httpRequest.Body, the last middleware will not see this.
This change is useful when some middleware reads httpRequest.Body to
perform some logic, and assigns a new ReadCloser to httpRequest.Body
(as body can be read only once). One example is authentication middleware that needs to read the body to validate signature.
> Last middleware should use the request passed by preceding middleware.

- api/server/server.go
The purpose of the PR is to expose an API in the extension manner, so the developers can use this to call the functions inside the extensions, specifically, listeners (note, that existing middleware `CallFunction` can be consumed only within the middleware, but not the listeners). So, given refactoring brings capabilities of the listeners to the same level of the middleware.
There is no impact to existing API.
New method suppose to be (or become) fewer HTTP-aligned.
Please note, that, eventually, this method should become trigger-agnostic and just accept a call for the execution, so any HTTP-(or whatever)-specific configuration should happen outside of this method to give unimaginable freedom of choice.
> Expose func call as the extensions API

- docker-compose.yml
1) fnserver dind requires privileged mode
2) mysql should be in sync with test.sh/api_test.sh mysql version to avoid errors such as
msg="couldn't ping db" error="this authentication plugin is not supported" url="root:root@tcp(db:3306)/funcs
TODO: fix/investigate why fnserver fails on latest mysql.
> fn: docker compose fixups

- api/server/gin_middlewares.go
- api/server/server.go
- docs/operating/options.md
Fixes https://github.com/fnproject/fn/issues/996
Added `FN_API_CORS_HEADERS` to make allowed CORS headers configurable. 
`FN_API_CORS` variable changed to `FN_API_CORS_ORIGINS` to make it consistent with the new `FN_API_CORS_HEADERS`
/cc @rdallman @adoublebarrel
> Added FN_API_CORS_HEADERS for configuring CORS headers

- api/agent/agent.go
- api/agent/agent_test.go
- api/agent/call.go
- api/agent/func_logger.go
- api/agent/slots.go
- api/agent/syslog.go
- api/agent/syslog_test.go
- api/datastore/sql/migrations/13_add_syslogurl_app.go
- api/datastore/sql/sql.go
- api/models/app.go
- api/models/call.go
- api/server/apps_test.go
- docs/operating/logging.md
- docs/swagger.yml
users may specify a syslog url[s] on apps now and all functions under that app
will spew their logs out to it. the docs have more information around details
there, please review those (swagger and operating/logging.md), tried to
implement to spec in some parts and improve others, open to feedback on
format though, lots of liberty there.
design decision wise, I am looking to the future and ignoring cold containers.
the overhead of the connections there will not be worth it, so this feature
only works for hot functions, since we're killing cold anyway (even if a user
can just straight up exit a hot container).
syslog connections will be opened against a container when it starts up, and
then the call id that is logged gets swapped out for each call that goes
through the container, this cuts …
> add user syslog writers to app

- api/agent/agent_test.go
- api/agent/call.go
- api/agent/config.go
- api/agent/lb_agent.go
- api/common/io_utils.go
- api/models/error.go
Currently, LimitRequestBody() exists to install a
http request body size in http/gin server. For production
enviroments, this is expected to be used. However, in agents
we may need to verify/enforce these size limits and to be
able to assert in case of missing limits is valuable.
With this change, operators can define an agent env variable
to limit this in addition to installing Gin/Http handler.
http.MaxBytesReader is superior in some cases as it sets
http headers (Connection: close) to guard against subsequent
requests.
However, NewClampReadCloser() is superior in other cases,
where it can cleanly return an API error for this case alone
(http.MaxBytesReader() does not return a clean error type
for overflow case, which makes it difficult to use it without
peeking into its …
> fn: agent MaxRequestSize limit

- api/agent/agent.go
- api/agent/agent_test.go
- api/agent/data_access.go
- api/agent/hybrid/client.go
- api/agent/hybrid/nop.go
- api/datastore/internal/datastoreutil/metrics.go
- api/datastore/mock.go
- api/datastore/sql/sql.go
- api/datastore/sql/sql_test.go
- api/logs/mock.go
- api/logs/s3/s3.go
- api/models/logs.go
- api/models/mq.go
- api/mqs/bolt.go
- api/mqs/memory.go
- api/mqs/mock.go
- api/mqs/new.go
- api/mqs/redis.go
- api/server/runner_test.go
As part of an agent's graceful shutdown, we should also flush and close any resources associated with its underlying _DataAccess_ implementation. This includes adding the ability to close the underlying Datastore, Logstore and MessageQueue, which are extended to implement _io.Closer_.
> Implement graceful shutdown of agent.DataAccess

- api/server/runner_async_test.go
- api/server/server.go
This change adds method `WithAdminServer` to fn server which enables to have the following paths available on server running on different port than the API server:
- /version
- /metrics
- /debug
This is useful when you want to keep these for 'internal' usage only, not to be exposed by the API.
The default behavior is backward compatible, that means all paths available on the API server only (no admin server running).
/cc @rdallman @treeder @vshiva @zootalures
> Admin server for paths which are not part of API

- api/server/gin_middlewares.go
- api/server/server.go
- api/server/stats.go
This change adds support for capturing metrics over all api endpoints.
3 new metrics views available:
`api/request_count` - Count of API requests started, supporting tags: `path`,`mathod`
`api/response_count` - API response count, supporting tags: `path`,`method`,`status`
`api/latency` - Latency distribution of API requests, supporting tags: `path`,`method`,`status`
Metrics definition is inspired by opencensus' http plugin: `https://github.com/census-instrumentation/opencensus-go/blob/master/plugin/ochttp/stats.go`
This is implemented using gin middleware, which uses the handler path, not the actual request path to keep the number of measure metrics smaller. (eg. use `/v1/apps/:app` instead of `/v1/apps/myrealapp`).
> Api metrics

- api/agent/agent.go
- api/agent/agent_test.go
- api/agent/call.go
- api/agent/config.go
- api/agent/drivers/docker/docker.go
- api/agent/drivers/docker/docker_pool.go
- api/agent/drivers/docker/docker_test.go
- api/agent/drivers/driver.go
- api/agent/slots.go
- api/datastore/sql/migrations/14_add_tmpfs_size_route.go
- api/datastore/sql/sql.go
- api/models/call.go
- api/models/route.go
- api/models/route_test.go
- images/fn-test-utils/fn-test-utils.go
*) read-only Root Fs Support
*) removed CPUShares from docker API. This was unused.
*) docker.Prepare() refactoring
*) added docker.configureTmpFs() for size limited tmpfs on /tmp
*) tmpfs size support in routes and resource tracker
*) fix fn-test-utils to handle sparse files better in create file
> fn: size restricted tmpfs /tmp and read-only / support

- api/agent/agent.go
- api/agent/agent_test.go
- api/agent/config.go
- docs/operating/options.md
This change sets root filesystem as read-only by default.
This behavior can be disabled via setting the
FN_DISABLE_READONLY_ROOTFS
environment variable.
> fn: read-only root fs becomes default

- api/agent/lb_agent.go
- api/runnerpool/ch_placer.go
- api/runnerpool/naive_placer.go
Moved retry interval as placer member variable for time-being.
> fn: cleanup of unused/global constants in lb agent

- api/agent/agent.go
- api/agent/call.go
- api/agent/lb_agent.go
- api/agent/lb_agent_test.go
- api/agent/protocol/factory.go
- api/agent/protocol/json_test.go
- api/agent/pure_runner.go
- api/runnerpool/ch_placer.go
- api/runnerpool/naive_placer.go
- api/runnerpool/runner_pool.go
- test/fn-api-tests/calls_test.go
- test/fn-api-tests/exec_test.go
- test/fn-api-tests/formats_test.go
- test/fn-api-tests/utils.go
- test/fn-system-tests/exec_test.go
Timeout setting in routes now means "maximum amount
of time a function can run in a container".
Total wait time for a given http request is now expected
to be handled by the client. As long as the client waits,
the LB, runner or agents will search for resources to
schedule it.
> fn: user friendly timeout handling changes

- api/server/gin_middlewares.go
If the there is an api request with url that doesn't match any route, the url end up being as empty string, which causes opencensus to report:
level=error msg="opencensus prometheus exporter err" error="inconsistent label cardinality"
This fix causes such a case to report the metric with url as 'invalid' -- this is convenient because we don't want to report the original url as it would increase the metrics cardinality.
/cc @rdallman @skinowski
> unmatched api handler reported as 'invalid' in api metrics

- api/agent/runner_client.go
In LB Agent (runner client), when a runner responds with NACK, the sender go routine may receive an EOF. With this change, we stop logging EOF from sender side.
> fn: LB agent: EOF from runner is normal in nack cases

- api/agent/runner_client.go
- api/runnerpool/ch_placer.go
- api/runnerpool/naive_placer.go
With this PR, runner client translates too busy errors
from gRPC session and runner itself into Fn error type.
Placers now ignore this error message to reduce unnecessary
logging.
> fn: LB agent: reduce 'Too Busy' error logs

- api/agent/lb_agent.go
In some cases could be useful to pass Agent configurations to the
LnAgent constuctor, this small change adds a new constructor which
accepts an agent configuration as additional parameter.
> Add a LBAgent constructor which accept AgentConfig

- api/agent/runner_client.go
Before this change, we assumed data may end up in a container
once we placed a TryCall() and if gRPC send failed, we did not
retry. However, a send failure cannot result in data in a
container, since only upon successful receipt of a TryCall can
pure-runner schedule a call into a container. Here we trust
gRPC and if gRPC layer says it could not send a msg, then
the receiver could not have received the message fully.
> fn: lb-agent: Initial TryCall result can be retriable.

- api/agent/agent.go
- api/agent/func_logger.go
- api/agent/lb_agent.go
- api/agent/pure_runner.go
- api/agent/runner_client.go
- api/runnerpool/ch_placer.go
- api/runnerpool/naive_placer.go
- grpcutil/dial.go
Scan through all log lines to add context logging where (I think) it's appropriate. 
This doesn't deal with context fields transfering over gRPC but should imrove the quality of some of the current runner messages when that is done
> Use context logging more to ensure context vars are present in log lines

- test/fn-system-tests/system_test.go
This was breaking system tests for me on macOS with VirtualBox installed.
This blacklist of interface names is definitely far from perfect, but this fixes it for me.
> Add vboxnet0 to the list of interface names that shouldn't be used for testing

- api/agent/static_pool.go
- api/agent/static_pool_test.go
Static pool is oriented for testing/basic usage and
as it's name implies it is a static pool. Therefore,
removing unnecessary/dead code.
> fn: remove dead code in static pool

- api/runnerpool/ch_placer.go
- api/runnerpool/naive_placer.go
- api/runnerpool/placer_stats.go
- api/runnerpool/runner_pool.go
- api/server/server.go
- system_test.sh
- test/fn-system-tests/.gitignore
- test/fn-system-tests/exec_test.go
- test/fn-system-tests/system_test.go
This change adds basic metrics to naive and consistent
hash LB placers. The stats show how many times we scanned
the full runner list, if runner pool failed to return a
runner list or if runner pool returned an empty list.
Placed and not placed status are also tracked along with
if TryExec returned an error or not. Most common error
code, Too-Busy is specifically tracked.
If client cancels/times out, this is also tracked as
a client cancel metric.
For placer latency, we would like to know how much time
the placer spent on searching for a runner until it
successfully places a call. This includes round-trip
times for NACK responses from the runners until a successful
TryExec() call. By excluding last successful TryExec() latency,
we try to exclude function execution & runner container …
> fn: introducing lb placer basic metrics

- Makefile
- api/logs/log.go
- api_test.sh
- helpers.sh
- system_test.sh
- test.sh
Moved allocation of listener ports for mysql/minio/postgres
to helper script with a list of service list names.
> fn: test scripts should use well defined ports

- .circleci/config.yml
- Makefile
- api_test.sh
- helpers.sh
- system_test.sh
- test.sh
*) Tests should be consistent when run from makefile versus
running these test scripts from command line. Let go use
GOMAXPROCS instead of hardcoded 4 cpus in Makefile.
*) Moved docker pull for specific image versions into
helpers scripts as well. Easier to maintain image version
for tests in the same place.
*) Minor Makefile cleanup: removed unused makefile targets.
> fn: remove confusing parallelism in test scripts

- api/agent/agent.go
- api/agent/call.go
- api/agent/lb_agent.go
- test/fn-system-tests/exec_test.go
- test/fn-system-tests/system_test.go
Similar to LB Agent call overrider, this PR adds Agent overrider
for Agents to modify/analyze a Call/Extensions during GetCall().
With this PR, we end up with 3 points where a service-provider
might override things:
1) LB GetCall() interception
2) Pure Runner GetCall() interception
3) Pure Runner drivers.driver.CreateCookie() interception
> fn: agent call overrider

- api/runnerpool/placer_stats.go
This is a small tweak to the placer latency stats. If we have a cluster of values
around the 1-2s mark, then having a single relatively broad bucket that captures
the (1s, 10s] range will obscure that. In particular, typical Prometheus quartile
estimates may be distorted by this bucket size.
We should probably do something better here - either let the end-user inject their distributions, or perhaps generate a log-linear spread across likely values with far more intervals.
> Add a finer-grained view for placer latency metrics

- docs/swagger_v2.yml
The code does not produce errors in the shape specified by the swagger, causing the generated client to explode on errors.
This change removed the error wrapper from the swagger, bringing the two views into line.
> Removing Swaggerv2 error wrapping

- api/datastore/datastoretest/test.go
- api/datastore/internal/datastoreutil/metrics.go
- api/datastore/internal/datastoreutil/validator.go
- api/datastore/mock.go
- api/datastore/sql/sql.go
- api/models/annotations.go
- api/models/app.go
- api/models/datastore.go
- api/models/fn.go
- api/models/trigger.go
- api/models/trigger_test.go
- api/server/apps_list.go
- api/server/apps_test.go
- api/server/apps_v1_list.go
- api/server/fns_list.go
- api/server/fns_test.go
- api/server/server.go
- api/server/trigger_list.go
- api/server/trigger_test.go
- fnext/datastore.go
Pushes datastore cursor creation and manipulation down into the datastore level, from the api layer. This gives complete freedom to datastore implementations to handle cursors in whatever format they desire.
Also changes the generations of names in the test suite so they aren't created in the same order as the id's, this was hiding the fact that triggers where not in fact being sorted by Name as per spec. This change led to a few edits in older tests.
> List Cursor management moved into datastore layer.

- api/datastore/datastoretest/test.go
Quick fix in datastore tests so that it errors rather than segfaults in the event of failure.
> Check error on triggers with non-existent app test

- api/agent/agent.go
- api/agent/agent_test.go
- api/agent/drivers/docker/docker.go
- api/agent/drivers/register.go
- api/datastore/datastore.go
- api/datastore/sql/dbhelper/dbhelper.go
- api/datastore/sql/mysql/mysql.go
- api/datastore/sql/postgres/postgres.go
- api/datastore/sql/sql.go
- api/datastore/sql/sqlite/sqlite.go
- api/logs/log.go
- api/logs/s3/s3.go
- api/server/defaultexts/defaultexts.go
- api/server/server_test.go
- test/fn-system-tests/system_test.go
This makes agent drivers run-time resolved to enable people to build an API or LB service binary that omits docker dependencies.
> Make Docker an optional component at compile time.

- api/agent/agent.go
- api/agent/evictor.go
- api/agent/evictor_test.go
- api/agent/resource.go
- api/agent/slots.go
- docs/operating/options.md
Previously, the hot-container eviction logic used
number of waiters of cpu/mem resources to decide to
evict a container. An ejection ticker used to wake up
its associated container every 1 sec to reasses system
load based on waiter count. However, this does not work
for non-blocking agent since there are no waiters for
non-blocking mode.
Background on blocking versus non-blocking agent:
*) Blocking agent holds a request until the
the request is serviced or client times out. It assumes
the request can be eventually serviced when idle
containers eject themselves or busy containers finish
their work.
*) Non-blocking mode tries to limit this wait time.
However non-blocking agent has never been truly
non-blocking. This simply means that we only
make a request wait if we take some action in
the …
> fn: agent eviction revisited

- api/agent/drivers/docker/docker.go
- api/agent/drivers/docker/registry.go
- api/agent/drivers/docker/registry_test.go
Start using URL parsed ServerAddress and its subdomains
for easier image ensure/pull in docker driver. Previous
code to lookup substrings was faulty without proper
URL parse and hostname tokenization. When searching
for a registry config, if image name does not contain
a registry and if there's a private registry configured,
then search for hub.docker.com and index.docker.io. This
is similar to previous code but with correct subdomain
matching.
> fn: cleanup of docker private registry code

- api/agent/drivers/docker/registry.go
- api/agent/drivers/docker/registry_test.go
- docs/operating/private_registries.md
Renamed DOCKER_AUTH with FN_ prefix to clarify the purpose. Docker
does not use this variable.
New tests to clarify the repo/auth-config behavior.
> fn: tests for private repo auth and rename DOCKER_AUTH

- api/agent/lb_agent_test.go
- api/runnerpool/ch_placer.go
- api/runnerpool/naive_placer.go
- api/runnerpool/placer_config.go
- api/runnerpool/placer_stats.go
- api/runnerpool/placer_tracker.go
- api/server/server.go
- test/fn-system-tests/system_test.go
Previously, LB Placers worked hard as long as
client contexts allowed for. Adding a Placer
config setting to bound this by 30 seconds by
default.
The new timeout is not accounted during actual
function execution and only applies to the amount
of wait time in Placers when the call is not
being executed.
> fn: New timeout for LB Placer

- api/runnerpool/placer_stats.go
[0, 2, 3, 4, 8, 16, 32, 64, 128, 256] gives us:
s >= 0
s >= 2
s >= 3
and so on for better observability.
> fn: adjusting LB retry view buckets

- api/server/init.go
- docs/operating/options.md
https://github.com/fnproject/fn/issues/1141
- What I did
`getEnv` and `getEnvInt` now test to see if `{key}_FILE` is set after testing `{key}`.  If it is set it reads the value from the specified file.
- How I did it
I searched for the point where the environment variables were loaded and added a small feature to it.
Build the docker image as usual, then
```sh
echo 8081 > /tmp/test_var
docker run -v /tmp/test_var:/run/secrets/test_var -v /var/run/docker.sock:/var/run/docker.sock -e FN_PORT_FILE=/run/secrets/test_var -i {image}
```
You should see Fn server running on port 8081
Support `_FILE` postfixes for environment variables to be loaded from file.
- One moving picture involving robots (not …
> Support _FILE postfixes for environment variables

- api/agent/agent_test.go
- api/agent/call.go
- api/agent/config.go
- api/agent/lb_agent.go
- api/server/server.go
- api/server/server_options.go
- api/server/server_test.go
moves the config option for max request size up to the front end, adds the env
var for it there, adds a server test for it and removes it from agent. a
request is either gonna come through the lb (before grpc) or to the server, we
can handle limiting the request there at least now, which may be easier than
having multiple layers of request body checking. this aligns with not making
the agent as responsible for http behaviors (eventually, not at all once route
is fully deprecated).
more easing of #1138 and again a quick rebase
> move max_request_size from agent to server

- docker-compose.yml
v3.5 allows network static name binding which allows successfully bypass docker network name through FN_DOCKERS_NETWORK
Note, API upgrade is required per the following discussion: https://github.com/docker/compose/issues/6113
- What I did
compose version changed from 3 to 3.5
```bash
docker-compose up -d
docker network | grep "fn-network"
docker inspect fn-network
docker-compose down
```
Compose network static name binding via API upgrade from 3 to 3.5
> Upgrade compose version from 3 to 3.5

- api/server/runner.go
Fixes issue https://github.com/fnproject/fn/issues/1150 by exposing a public method `func (s *Server) ServeRoute(c *gin.Context, app *models.App, route *models.Route) error` on Server that can be invoked by custom route handlers.
> Expose ServeRoute method on Server to allow extensions to plugin custom route handling

- api/models/app.go
Trivial one-line fix to make `App.Equals()` compare SyslogURL too.
> Equality methods on app should include syslogurl field

- api/agent/drivers/docker/docker_client.go
- api/agent/stats.go
- api/common/stats_utils.go
- api/logs/s3/s3.go
- api/runnerpool/placer_stats.go
- api/server/gin_middlewares.go
- api/server/server.go
- api/server/stats.go
- cmd/fnserver/main.go
- test/fn-system-tests/system_test.go
*) View latency distribution is now an argument
in view creation functions. This allows easier
override to set custom buckets. It is simplistic
and assumes all latency views would use the same
set, but in practice this is already the case.
*) Moved API view creation to main, this should not
be enabled for all node types. This is consistent with
the rest of the system.
*) Some stats with Distribution did not have their buckets
configured, this is now plumbed in.
> fn: stats view/distribution improvements

- api/agent/slots.go
Even though this is not being used cryptographically SHA1 is considered as an untrusted algorithm in many domains. 
For safety's sake use SHA256 in favour of SHA1 for slot calculations
> Use sha256 for slot token

- api/agent/state_trackers.go
Round still leaves the unit as duration. This PR fixes this to ensure msec conversion.
> fn: fix math error in calculating msecs in container states

- api/agent/stats.go
- cmd/fnserver/main.go
Operators can best pick the proper range for their operating
environment. Default cmd/fnserver uses some sensible
defaults.
> fn: moving opencensus distribution buckets out of agent

- api/agent/lb_agent_test.go
- api/agent/pure_runner.go
- api/agent/runner_client.go
- api/agent/static_pool.go
- api/agent/static_pool_test.go
- api/common/tls_utils.go
- api/runnerpool/runner_pool.go
- api/server/server.go
- grpcutil/dial.go
SSL related FN_NODE_CERT (and related) settings are
not very clear today. Removing this in favor of a
simple map of tls.Config objects. Three keys are
provided for this map:
TLSGRPCServer
TLSAdminServer
TLSWebServer
which correspond to server TLS settings for the
associated services. These three service keys
are detected during startGears() execution and
SSL/TLS is enabled accordingly in web/admin listeners.
Operators/implementers can further add more
keys to the map and add their own TLS config.
pool.PKIData is now removed. This is a very limited TLS
configuration and tls.Config in crypto/tls provides this
already.
Providing some utility functions to cover the old functionality
in common/tls_utils which now exposes a few simple functions
to set ca, clientCA, cert/key, etc.
> fn: SSL config adjustments

- api/agent/agent.go
- api/agent/agent_test.go
- api/agent/call.go
- api/agent/syslog.go
- api/agent/syslog_test.go
- api/models/call.go
This fixes #1146. 
I added the AppName to models.Call in order to be able to write it out in the logs.
Verified by running unit tests and manually setting the app sys-log and verifying correct logs are being sent to papertrail.
> Change the syslog format to use app_name instead of app_id

- api/models/fn.go
- api/server/fn_annotator.go
- api/server/fn_annotator_test.go
- api/server/fns_get.go
- api/server/fns_list.go
- api/server/fns_test.go
- api/server/server.go
- api/server/server_test.go
- api/server/trigger_get.go
- api/server/trigger_list.go
- docs/swagger_invoke.yml
- test/fn-system-tests/system_test.go
Clone of the trigger work to inject invoke urls into the annotations
on a fn when it is returned from the server.
> Fns now annotated with invoke urls, as per triggers

- api/server/fns_create.go
- api/server/fns_test.go
- api/server/trigger_create.go
- api/server/trigger_test.go
- What I did
Add trigger annotation so that you do not have to get the trigger to have its http endpoint
- How I did it
Called the annotator from trigger create
Create a trigger and check annotations for the http endpoint
Annotate httpendpoint to trigger on create
https://giphy.com/embed/CgfteGy1ZPYPu
Fixes #1178
> Add annotation to trigger on create if endpoints are enabled

- api/agent/agent_test.go
- api/agent/call.go
- api/agent/config.go
- api/agent/func_logger.go
closes #1147 
- What I did
added an env var FN_DISABLE_DEBUG_USER_LOGS to keep user logs from being logged at debug level. whether they're being logged to stderr is dependent on log level, even if it's info this will be a speedup, and if the level is in debug, it's likely a production installation will not want to be able to access these (yet still want debug logs for the system). 
start it up
add ability to disable user function logs to debug logs
> disable user function logs at debug level configuration

- api/server/trigger_update.go
NA
- What I did
Code fix to preserve right context when call is made to datastore.UpdateTrigger.
- How I did it
One line fix
Create a middleware to set some value in context.
Create app, fn, trigger
Update trigger
Before fix: verify that the value is not present in context when seen in UpdateTrigger method.
After fix: verify that the value is present in context.
Pass the right context object in call to datastore.UpdateTrigger
> Pass right context in call to datastore.UpdateTrigger

- api/agent/call.go
Fixes https://github.com/fnproject/cli/issues/392
The issue was on the server-side (not on the CLI), and it affects all FDKs.
- What I did
Sets required FN_PATH environment variable in models.Call to "/invoke" for direct fn invocations.
> Fixes direct invoke call model

- api/agent/agent.go
- api/agent/config.go
- api/agent/drivers/docker/docker.go
- api/agent/drivers/driver.go
fixes #1101
additional context:
* this was introduced in docker 1.13 (1/2017), we require docker 17.10
(10/2017), this should not have any issues dependency-wise, as `docker-init`
is in the docker install from that point in time. unless explicitly removed,
it should be in the dind container we use as well...
* the PR that introduced this to docker is
https://github.com/moby/moby/pull/26061 for additional context
* it may be wise to put this through some paces, if anybody has any...
interesting... function containers. the tests seem to work fine, however, and
this shouldn't be something users have to think about (?) at all, just
something that we are doing. this isn't the default in docker for
compatibility reasons, which is maybe a yellow flag but I am not sure tbh
* i've defaulted this …
> use tini to run every container

- api/agent/runner_client.go
- api/server/error_response.go
Currently, if a client closes an HTTP connection to the server in the middle of a request, this results in the server logging and attempting to respond with an HTTP 500 error. Instead, we should log that the request was canceled and stop further processing.
> Gracefully handles client request cancelations, instead of treating treating them as server errors

- api/models/error.go
- api/server/error_response.go
Handle context Cancel (client closed connection) with special error code HTTP 444. We merely set the status code in this case to make sure stats/metrics record the error code.
> fn: handle client connection close errors

- api/agent/drivers/docker/docker.go
- api/agent/drivers/docker/docker_client.go
With this change, we start tracking latencies in docker wrapper. This information is already in opencensus spans, however for environments where there's no open tracing server available, it's beneficial to have them in prometheus as well.
Docker exit codes are also now being tracked, which replaces OOM only counter now.
Exit codes, for example are as follows:
```
fn_docker_exits{api_name="docker_wait_container",exit_status="ctx_canceled",fn_appname="fn-http-func",fn_path="/fn-http-func"} 1
fn_docker_exits{api_name="docker_wait_container",exit_status="exit_137",fn_appname="fn-http-func",fn_path="/fn-http-func"} 2
```
and:
```
fn_docker_api_error{api_name="docker_inspect_image",fn_appname="fn-http-func",fn_path="/fn-http-func"} 1
fn_docker_api_error{api_name="docker_wait_container",fn_appnam …
```
> fn: docker driver stats/metrics for prometheus

- api/models/config.go
The config equality test doesn't check that keys exist between config
maps. Meaning that when two maps, both with a single, yet differing
key, with the lefts value being "", the default string, are compared they are
considered equal.
This change uses the two value assignment version of the map get,
allowing it to test for key existence.
> Adds key existence check to config equality

- api/datastore/mock.go
- api/datastore/sql/migratex/migrate.go
- api/datastore/sql/migrations/18_add_fnid_calls.go
- api/datastore/sql/sql.go
- api/logs/metrics/metrics.go
- api/logs/mock.go
- api/logs/s3/s3.go
- api/logs/testing/test.go
- api/models/call.go
- api/models/logs.go
- api/server/call_get.go
- api/server/call_list.go
- api/server/server.go
- docs/swagger_v2.yml
The V2 Calls api endpoints have been added beneath fns:
/fns/{fnID}/calls
/fns/{fnID}/calls/{callID}
The S3 implementation forces our hand as we if we want to list Calls
under a Fn, we have to use the FnID as a prefix on the object names,
which mean we need it to look up any Call. It also makes sense in
terms of resource hierarchy.
These endpoints can optionally be disabled (as other endpoints), if a
service provider needs to provide this functionality via other means.
The 'calls' test has been fully migrated to fn calls. This has been
done to reduce the copy pasta a bit, and on balance is ok as the
routes calls will be removed soon.
> Support Fn Calls on V2 api

- api/server/server.go
Currently, when the calls endpoints are disabled a 501 is
returned. While this is technically correct, it's not hard to see this
causing trouble when people tend to create 5xx roll up alerting
metrics.
This changes it to a 410, Gone, response, which is close enough and
should allow clients to know what's going on.
> Change not present v2 call endpoint respone to Gone

- api/server/gin_middlewares.go
- api/server/server.go
This allows to time limit slow/malicious clients when
reading HTTP headers. In GetBody() buffering, same timeout
can be used to time limit to give consistent I/O wait
limits for the service in addition to per handler
imposed limits we already have.
> fn: add http.Server options for web/admin/grpc services in server

- api/agent/drivers/docker/docker.go
- api/agent/drivers/docker/docker_client.go
With this change, we no longer allow docker client AttachToContainerNonBlocking
to block on Success channel more than our context deadline/timeout.
> fn: check context timeout when waiting for non-blocking attach

- api/agent/data_access.go
- api/datastore/sql/migrations/19_add_fnid_logs.go
- api/datastore/sql/sql.go
- api/logs/metrics/metrics.go
- api/logs/mock.go
- api/logs/mock_test.go
- api/logs/s3/s3.go
- api/logs/testing/test.go
- api/logs/validator/validator.go
- api/models/error.go
- api/models/logs.go
- api/server/call_logs.go
- api/server/hybrid.go
- api/server/server.go
- docs/swagger_v2.yml
Copies the log endpoints up to the V2 endpoints, in a similar way to
the call endpoints.
The main change is to when logs are inserted into S3. The signature of
the function has been changed to take the whole call object, rather
than just the app and call id's. This allows the function to switch
between calls for Routes and those for Fns. Obviously this switching
can be removed when v1 is removed.
In the sql implementation it inserts with both appID and fnID, this
allows the two get's to work, and the down grade of the
migration. When the v1 logs are removed, the appId can be dropped.
The log fetch test and error messages have been changed to be FnID specific.
> Copy logs up to v2 endpoints

- api/agent/agent.go
- api/agent/config.go
- api/agent/lb_agent.go
agent/lb-agent/runner roles execute call.End() in the background
in some cases to reduce latency. With this change, we simplify this
and switch to non-background execution of call.End(). This fixes
hard to detect issues such as non-deterministic calculation of
call.CompletedAt or incomplete Call.Stats in runners.
Downstream projects if impacted by the now blocking call.End()
latency should take steps to handle this according to their requirements.
> fn: make call.End() blocking to reduce complexity

- api/agent/agent.go
- api/agent/agent_test.go
- api/agent/call.go
- api/agent/lb_agent.go
- api/agent/stats.go
- api/models/error.go
- api/server/runner_fninvoke_test.go
- api/server/runner_httptrigger_test.go
- api/server/runner_test.go
- test/fn-system-tests/exec_http_trigger_test.go
- test/fn-system-tests/exec_route_test.go
1) Early call validation and return due to cpu/mem impossible
to meet (eg. request cpu/mem larger than max-mem or max-cpu
on server) now emits HTTP Bad Request (400) instead of 503.
This case is most likely due to client/service configuration
and/or validation issue.
2) 'failed' metric is now removed. 'failed' versus 'errors'
were too confusing. 'errors' is now a catch all error case.
3) new 'canceled' counter for client side cancels.
4) 'server_busy' now covers more cases than it previously did.
> fn: agent/lb/runner error handling adjustments

- api/agent/agent.go
- api/agent/config.go
- api/agent/drivers/docker/cookie.go
- api/agent/drivers/docker/docker_pool.go
- api/agent/drivers/docker/docker_test.go
- api/agent/drivers/driver.go
I noticed  that http-stream doesn't work on docker4mac - this is because docker mounts volumes relative to the OSX host, not the docker VM. 
This change allows two directory roots for IOFS mounts one with respect to the docker host, one with respect to the agent itself.  The behaviour is conditional on both FN_IOFS_PATH and FN_IOFS_MOUNT_ROOT. 
I've also added the specified headers to the contract (proper HTTP versions rather than the old FN_DEADLINE) as dups , this makes java happy
```
docker run -v $(pwd)/maciofs:/iofs -eFN_LOG_LEVEL=debug  -e FN_IOFS_PATH=/iofs -e FN_IOFS_MOUNT_ROOT=$(pwd)/maciofs  --privileged -v /var/run/docker.sock:/var/run/docker.sock   -p8080:8080  --name fnserver --rm  fnproject/fnserver
```
> support configuration-based relative dirs (host and agent) for iofs

- api/agent/agent.go
- api/agent/call.go
- api/agent/config.go
- api/agent/drivers/docker/cookie.go
- api/agent/drivers/docker/docker_pool.go
- api/agent/drivers/docker/docker_test.go
- api/agent/drivers/driver.go
because what drivers.ContainerTask needs is another method, and we all know it
atoning for my sins the first time around. and yes, i refuse to use a cross
package exported constant (just think of the dep graphs)
this also uses `/tmp` inside the container
> clean up hardcoded lsnr.sock refs, move iofs to /tmp

- api/agent/agent.go
- api/agent/config.go
We tie container pausing with evictions, where if a container
is paused, then it is also eligible for eviction.
> fn: remove eviction timer to simplify eviction logic

- api/agent/call.go
- api/server/runner_fninvoke_test.go
- api/server/runner_httptrigger_test.go
- api/server/server_test.go
- images/fn-test-utils/Gopkg.lock
- images/fn-test-utils/fn-test-utils.go
this assures that Content-Type and Fn-Http-Status are set for an http-stream
function. it took some fixing up of the test utils code for the plumbing to
work, looking forward to deleting most stuff in fn-test-utils.go file around
each format -- had to update fdk-go to latest for http-stream support. this
only adds 1 test, since there's some machinery here, and would like to unblock
working on the http gateway simultaneously while adding a full suite of invoke
tests (this work can be parallelized)...
i added debug logs back to the debugging output. turns out this is useful, but
it can get noisy (only when things fail, hopefully).
> Stream test commence

- README.md
* None that I'm aware of.
- What I did
* Update docs links to point to the docs repo.
- How I did it
* Updated the URLs in README.md
* Tested links in a test file. Note the selinux.md file has not been moved to the new repo, but will be in a separate PR.
Update ReadMe links to point to new docs repo
Maeve uses the force
> Update ReadMe links to point to new docs repo

- api/server/call_logs.go
Currently, the log response is not compatible with the swagger
document.
This change removes the log wrapper that the old version required.
> Unwrap log response

- api/agent/agent.go
- api/agent/call.go
- api/server/runner_fninvoke.go
- api/server/runner_fninvoke_test.go
- api/server/runner_httptrigger_test.go
- images/fn-test-utils/fn-test-utils.go
the other formats had a gamut of tests, now http-stream does too. this makes
obvious some of its behaviors. some things changed / can change now that we
don't have pipes to worry about, the main one being that when containers blow
up now the uds client will get an EOF/ECONNREFUSED instead of the pipe getting
wedged up (allowing us to get the container error easily, previously). I made
my best 50% effort to make a reasonable error for when this happens (similar
to when http/json received garbage errors), open to ideas on verbiage / policy
there.
should be pretty straightforward. one thing to notice is that
http/json/default don't return our fancy new Fn-Http-Status or Fn-Http-H
headers... it's relatively easy to go add this to fdk-go just to test this,
but for invoke I'm really not sure we …
> Http stream invoke tests

- api/agent/agent.go
- api/agent/agent_test.go
- api/agent/drivers/docker/docker.go
- What I did
When pulling docker images to run the function, check if the Call has 'FN_REGISTRY_TOKEN' extension and use that token in the call to registry.
- How I did it
fnLB Call override will add the auth token as extension if the image is from a registry that needs authentication. The token is then sent to runner as Call extension. Runner uses it to pull image for the Call
> Use registry auth token from Call extensions to pull images

- api/agent/agent.go
*) removed faulty Idle state setter in runHot() since with
UDS wait, we need to wait until we can determine if a container
is idle. This is now moved to runHotReq().
*) evictor now more aggresive and no longer tied to pause
timer/configuration.
*) removed unnecessary optimization on timer=0 case for immediate
pause.
> fn: freezer/evictor adjustments

- api/agent/call.go
- api/server/runner_fninvoke.go
- api/server/runner_httptrigger.go
- test/fn-system-tests/exec_fn_test.go
Removing the repeated logic exposed some problems with the reponse
writers.
Currently, the trigger writer was overlaid on part of the header
writing. The main invoke blog writing into the different levels of the
overlays at different points in the logic.
Instead, by extending the types and embedded structs, the writer is
more transparent. So, at the end of the flow it goes over all the
headers available and removes our prefixes. This lets the invoke logic
just write to the top level.
Going to continue after lunch to try and remove some of the layers and
param passing.
> Initial Refactor

- api/agent/agent.go
- api/agent/agent_test.go
this mitigates a risk where by an FDK could create a UDS symlink to a non-relative path on the host which the agent would try to connect to - (e.g. /var/lib/docker.sock)  
this does not mandate that the socket is a symlink but does ensure that : 
* If it's a symlink it is relative to its own directory (this is strictly enforced, i don't allow things like "/dir/sock -> ../dir/sock") 
* That the symlink links to a socket 
I'm not checking perms here as the UDS client should be fine doing that.
> Add checks for unix socket destination to avoid FDK tricking agent into talking to non-relative dirs

- api/agent/agent.go
I think this is the bare minimum we should be doing if we're unable to close this. Possibly worth a retry too?
> Log failure to close fsnotify handle

- api/agent/agent.go
Fixed the fact that the http.Request sent through UDS in http-stream does not have a Context.
Old dispatch methods use CallInfo and provide the original request (which has a Context), but the new dispatch method for http-stream through UDS creates a new request and does not set the context there. I have merely added a `WithContext` call.
> Fix missing context on request sent through UDS

- api/agent/agent.go
Each container running http-stream functions has a UDS through which requests are piped, but only one request at a time. 
Therefore, the Transport for that socket should not maintain a large connection pool: it is not needed at all. This change reduces the idle connections to 1. Hopefully this reduces File Descriptors usage even further.
> Limit connection pool size on UDS: we should only need one per container

- api/models/error.go
- api/runnerpool/ch_placer.go
- api/runnerpool/naive_placer.go
- api/server/error_response.go
Loggable errors have a separate message that is logged only but is not part of the response.
> Add APIErrorWrapper so that underlying errors can be logged

- api/agent/agent.go
- api/agent/call.go
- api/agent/resource.go
- api/agent/resource_test.go
This simplifies resource tracker. Originally, logically we had
split the cpu/mem into two pools where a 20%
was kept specifically for sync calls to avoid
async calls dominating the system. However, resource
tracker may not be the best place to handle such call
prioritization. Given the improvements to the evictor, I think
we can get rid of this code in resource tracker
for time being.
> fn: remove async+sync separation in resource tracker

- api/agent/agent.go
- api/agent/evictor.go
- api/agent/evictor_test.go
If checkLaunch triggers evictions, it must wait
for these eviction to complete before returning.
Premature returning from checkLaunch will cause
checkLaunch to be called again by hot launcher.
This causes checkLaunch to receive an out of
capacity error and causes a 503.
The evictor is also improved with this PR and it
provides a slice of channels to wait on if evictions
are taking place.
Eviction token deletion is performed *after*
resource token close to ensure that once an
eviction is done, resource token is also free.
> fn: adding hot launcher eviction waiting

- README.md
Allows other Fn site links to jump to the top of the README rather than the gihub list of files.
- What I did
Added an anchor:  `<a id="top"></a>`
- How I did it
Edited
Doublechecked with a GitHub Wiki page. It works.
Add a 'top' anchor to landing page
Akecheta rides the Top of the ridge.
> Add a 'top' anchor to landing page

- api/server/gin_middlewares.go
- cmd/fnserver/main.go
Default fn server keys should be minimal (empty) since not
all stats have associated app name, fn id, etc.
API tags for requests should not include "status" as this is
part of responses.
> fn: default fnserver tag keys and api key adjustment

- api/agent/agent.go
* the dispatch span actually encloses dispatch and gives an accurate span now
* turning a call into an http request can't fail unless it's our fault, if
tests don't catch this, we don't deserve money
* moved http req creation inside of dispatch goroutine
there's further work to do cleaning up dispatch... removing the old formats
will make this slightly more clear, waiting for that. this was bugging me
anyway after seeing something else and was easy to fix up.
> small tweaks to dispatch

- api/common/logging.go
Currently the default time format, time.RFC3339, is used, which doesn't include any
subsecond resolution information. This makes it hard to understand the
ordering of log messages when viewing in a log aggregator, like
Kibana.
This change sets the TimestampFormat of the logrus JSONFormatter to
time.RFC3339Nano.
> Configure logrus to include nano seconds in log messages

- api/agent/agent.go
Let's not log evicted containers which would be context
canceled.
> fn: reduce logging for evicted containers

- CONTRIBUTING.md
Added explicit instructions in terms of where to place the cloned repo and initiate the build, without which it will (obviously) not work
> Added instructions related to GOPATH

- CONTRIBUTING.md
* at least a stub security bug section, this works as a policy most likely
until we can improve this (TODO we need an email for this!)
* adds info in CONTRIBUTING.md for creating helpful normal issues for us, this
is much the same info as the template
* coding style section. This was lacking, and led to wishy washy reviews. now
we have an official reference in place to point at for 'do this this way
please' and not just random opinions. everyone should read this if they
haven't! I have it bookmarked...
* info on creating useful commit messages and commit formatting, like code
reviews, its nice to have this in the contrib guide to reference when asking
people to do this so that it's not just a one off opinion
tried to make this pretty lax, the last thing i/we want is for the
contributing …
> improve contribution guide

- api/agent/agent.go
- api/agent/config.go
- api/agent/drivers/docker/docker.go
- api/agent/drivers/docker/docker_client.go
- api/agent/drivers/docker/docker_pool.go
Moving the timeout management of various docker operations
to agent. This allows for finer control over what operation
should use. For instance, for pause/unpause our tolerance
is very low to avoid resource issues. For docker remove,
the consequences of failure will lead to potential agent
failure and therefore we wait up to 10 minute.
For cookie create/prepare (which includes docker-pull)
we cap this at 10 minutes by default.
With new UDS/FDK contract, health check is now obsoleted
as container advertise health using UDS availibility.
> fn: cleanup of docker timeouts and docker health check

- api/agent/agent.go
- api/agent/state_trackers.go
- api/agent/stats.go
Prep work for future evictor enhancements. This PR adds state tag
to eviction stats.
> fn: add container state to eviction stats

- api/datastore/datastoretest/test.go
- api/datastore/sql/sql.go
#1294 
- What I did
Fixed buildFilterFnQuery in local datastore code to respect 'Name' filter.
Use 'name' parameter on v2/fns GET endpoint to filter function list by name. E.g. `curl "localhost:8080/v2/fns?app_id=MYAPPID&name=MYFUNC1"` 
Fixed filtering by name when getting function list
> Fix filtering by name when getting list of funcs

- api/agent/agent.go
- api/agent/agent_test.go
- api/agent/config.go
- api/agent/drivers/docker/cookie.go
- api/agent/drivers/docker/docker.go
- api/agent/drivers/docker/docker_client.go
- api/agent/drivers/driver.go
*) added a check for unneeded container remove if docker-pull fails
*) Max retries is now in config for testing
*) Hung docker repo to ensure timeout is honored
> fn: tests for hung and bad docker repo during docker-pull

- release.sh
This should enable go mod to accurately resolve Fn as a dependency
> Enable tagging to vx.y.z tags

- api/agent/agent.go
- api/agent/drivers/docker/cookie.go
- api/agent/drivers/docker/docker.go
- api/agent/drivers/docker/docker_pool.go
- api/agent/drivers/docker/docker_test.go
- api/agent/drivers/driver.go
- api/agent/drivers/mock/mocker.go
Now obsoleted driver.PrepareCookie() call handled image and
container creation. In agent, going forward we will need finer
grained control over the timeouts implied by the contexts.
For this reason, with this change, we split PrepareCookie()
into Validate/Pull/Create calls under Cookie interface.
> fn: cookie and driver api changes

- api/agent/call.go
- api/agent/drivers/docker/docker.go
- api/agent/func_logger.go
- api/agent/lb_agent.go
- api/agent/pure_runner.go
- api/common/io_utils.go
there's a racey bug where the logger is being written to when it's closing,
but this led to figuring out that we don't need the logger at all in pure
runner really, the syslog thing isn't an in process fn thing and we don't need
the logs from attach for anything further in pure runner. so this disables the
logger at the docker level, to save sending the bytes back over the wire, this
could be a nice little performance bump too. of course, with this, it means
agents can be configured to not log debug or have logs to store at all, and
not a lot of guards have been put on this for 'full' agent mode while it hangs
on a cross feeling the breeze awaiting its demise - the default configuration
remains the same, and no behavior changes in 'full' agent are here.
it was a lot smoother to make the …
> disable pure runner logging

- api/models/error.go
- api/server/runner_fninvoke.go
- api/server/runner_fninvoke_test.go
- api/server/server.go
- docs/swagger_invoke.yml
Closes: #1310
- Link to issue this resolves: #1310 
- What I did: changed Gin handler definition with some HTTP method validation for the sake of valid error message.
- How I did it: with no problem ;)
- How to verify it: call invoke handler with any http method except POST.
- One line description for the changelog: The following commit improves error status code and message for the cases when invoke path called with any HTTP method except HTTP POST
> Fix response message on invoke handler

- api/agent/agent.go
- api/agent/call.go
- api/agent/config.go
- api/agent/lb_agent.go
- api/models/error.go
FDK must respond with 200/502/504 to http requests. Any other status is invalid and container
must be terminated if that occurs. HTTP timeouts are also considered a shutdown reason
for the container.
With this PR, we trust http client to use the context timeout and therefore avoid spawning
a go-routine. This simplifies the flow and also avoids case of call.stderr.Close() executing before swapBack.
> fn: enforce container/FDK contract in dispatch

- api/agent/agent.go
- api/agent/agent_test.go
- api/agent/call.go
- api/agent/drivers/docker/docker.go
- api/server/apps_test.go
* for pure runner this turns it off for real this time.
* this also just makes the agent container type send stdout to stderr, since
we're not using stdout for function output anymore this is pretty
straightforward hopefully.
* I added a panic and some type checking printlns to ensure this is true for
pure_runner, both stdout and stderr are off, also added a unit test from agent
to ensure this behavior from its container type, which pure_runner utilizes
(no integration test though)
> actually disable stdout/stderr. stdout>stderr

- api/runnerpool/placer_stats.go
- api/runnerpool/placer_tracker.go
For the sake of completeness and also as defensive coding,
let's record client context cancel/timeout cases. In retry
reason, if error is same as client context (timeout/cancel),
we should not report as retry due to error. Similarly in
placed calls, do not flag the placed call as error if client
canceled or timedout. We track client context timeout/cancel
separately in addition to this.
> fn: placer stats and client context

- api/models/error.go
- test/fn-system-tests/exec_fn_test.go
Too-Busy 503 is a retriable error, this error
should be 504 instead. Fn LB will attempt to retry a 503.
> fn: container init timeout should be a 504

- api/agent/call.go
- api/agent/lb_agent.go
- api/agent/lb_agent_test.go
- api/agent/runner_client.go
- api/agent/stats.go
- api/runnerpool/runner_pool.go
- test/fn-system-tests/exec_runner_status_test.go
- test/fn-system-tests/system_test.go
This complements the API latency metrics available
on LB agent. In this case, we would like to measure
calls that have finished with the following status:
"completed"
"canceled"
"timeouts"
"errors"
"server_busy"
and while measuring this latency, we subtract the
amount of time actual function execution took. This
is not precise, but an approximation mostly suitable
for trending.
Going forward, we could also subtract UDS wait time and/or
docker pull latency from this latency as an enhancement
to this PR.
> fn: latency metrics for various call states

- api/agent/agent.go
- api/agent/stats.go
Adding tracker for UDS initialization during container start. This
complements our existing container state latency trackers and
docker-api latency trackers.
> fn: uds init wait latency metric in prometheus

- api/agent/agent.go
- vendor/modules.txt
There is no need to propagate CapacityFull to waitHot(). Instead
waitHot() can receive 503 which is easier to follow (and less
error prone) in handleCallEnd().
> fn: minor error code simplification

- docs/swagger_v2.yml
- What I did
Fixed the swagger spec to allow syslog-url in apps to be nullable, therefore enabling the possibility to distinguish between it being not set and it being explicitly set to an empty string.
The Fn server already handles that distinction, but the swagger did not allow clients to take advantage of that.
- How I did it
The swagger spec is changed to include the `x-nullable` notation for `syslog-url` in the `App` definition.
Regenerate clients, see that the generated code changes according to the language of choice.
Fixed the swagger spec to allow syslog-url in apps to be nullable, therefore enabling the possibility to distinguish between it being not set and it being explicitly set to an empty string.
> Make syslog-url nullable in the swagger so it can be explicitly unset

- .circleci/config.yml
- Makefile
- api/agent/agent.go
- api/agent/drivers/docker/docker_client.go
- api/agent/resource.go
- api/common/logging.go
- api/common/tls_utils.go
- api/datastore/sql/migratex/migrate.go
- api/datastore/sql/migrations/10_add_app_id.go
- api/datastore/sql/mysql/mysql.go
- api/datastore/sql/sql.go
- api/datastore/sql/sqlite/sqlite.go
- api/mqs/bolt/bolt.go
- api/server/init.go
- images/fn-test-utils/fn-test-utils.go
gosec severity=medium passes, all severity=low errors are from unhandled
errors, we have 107 of them. tbh it doesn't look worth it to me, but maybe
there are a few assholes even itchier than mine out there. medium has some
good stuff in it, and of course high makes sense if we're gonna do this at
all.
this adds some nosec annotations for some things like sql sprintfs where we
know it's clean (we're constructing the strings with variables in them). fixed
up other spots where we were sprinting without need.
some stuff like filepath.Clean when opening a file from a variable, and file
permissions, easy stuff...
I can't get the CI build to shut up, but I can locally get it to be pretty
quiet about imports and it just outputs the gosec output. fortunately, it
still works as expected even when …
> add gosec scanning to ci

- api/server/runner_fninvoke.go
- api/server/runner_fninvoke_test.go
back when we streamed responses out from the container, we set this header
regardless of whether the task ran or not. now, we're setting this header at
the end since we're doing buffering, only if the task runs successfully atm.
we can change to the old policy pretty readily if we want to, up for
discussion. as this patch presents it, it's just adding a test that it exists
in the normal case and the timeout case, and adding the timeout case. however,
other relevant cases exist, like fdk protocol errors, and we can whitelist
those each or just cover all errors, even if the call was never executed, up
to us. when we add streaming, the plumbing goes back to the way it was where
we just add this at some point before the container writes any headers out of
it, and we can pick what level to do …
> adds tests for Fn-Call-Id, and adds for timeouts

- grpcutil/dial.go
- What I did
Format error string in grpc dial function to reduce log spam.
- How I did it
Changed the error that is returned.
Read the logs.
Reduce log spam from grpc dials
> Format error string and return do not log error reduce log spamming

- .circleci/config.yml
gosec being in ./bin is causing issues for release script with a dirty working
directory, moves the gosec binary to $GOPATH/bin
go1.11.4 is a security patch
> update go1.11.4 / fix gosec

- api/agent/lb_agent_test.go
- api/agent/pure_runner.go
- api/agent/runner_client.go
- api/agent/static_pool.go
- api/agent/static_pool_test.go
- api/runnerpool/runner_pool.go
- test/fn-system-tests/system_test.go
Clients/Servers should be allowed to pass options to
grpc server or grpc dial. As an example, client and
server keepalive settings are used in system tests
to demonstrate.
MTLSRunnerFactory type is also removed as this
hinders extensibility.
> fn: allow server and client dial keepalive settings

- api/agent/pure_runner.go
- api/agent/stats.go
- cmd/fnserver/main.go
- test/fn-system-tests/system_test.go
Simple metric to show number of status call executions with
cache/success prometheus tags.
> fn: add status call prometheus metrics

- api/agent/drivers/docker/docker_client.go
i'd say this is a nit but idk just trying to discourage this kinda thing in
general, it gets out of hand passing around loggers when they can just get
tucked into the context like everything else
will add the one from https://github.com/fnproject/fn/pull/1363 after it gets merged up
> remove logger arg from docker driver

- CONTRIBUTING.md
- go.mod
- noop/noop1/go.mod
- noop/noop2/go.mod
added some pointers with commands for forking fn and making contributions to
it. i also did a test of using go1.11 and cloning the repo to somewhere
outside of my $GOPATH and then doing `make build` and it required making a
small change to the noop stuff in order for the build to work. pretty sweet
that the gopath thing died, woo, updated the contribution guide to reflect
this, as well.
> fix build, add pointers for forking

- api/agent/agent.go
- api/agent/config.go
- api/agent/drivers/docker/cookie.go
- api/agent/drivers/docker/docker.go
- api/agent/drivers/docker/docker_client.go
- api/agent/drivers/docker/image_cache.go
- api/agent/drivers/docker/image_cache_test.go
- api/agent/drivers/docker/image_cleaner_test.go
- api/agent/drivers/driver.go
Introducing a new image cleaner background job in docker driver. If enabled (with FN_IMAGE_CLEAN_MAX_SIZE set > 0 bytes), the cleaner performs the following
at startup:
1) list images to populate the image cache, once this completes, then
2) in a loop, wait for notifications from image cache if/when total cache size exceeds max.
Periodically pick a LRU image and delete it in docker in order to meet the cache size constraint.
The cleaner is not tested and will likely fail if docker build environment is present since these
can leave intermediate and/or dangling images. Also the cleaner expects that no outside manual
action is performed on these images. For example, a force removal can leave an image untagged/dangling. Cleaner interaction with these environments/cases is not tested. …
> remove unused images when total image size exceeds a limit

- api/agent/runner_client.go
- api/runnerpool/placer_tracker.go
If a customer function fails due to an issue with the function itself (e.g. customer-side timeout or usage of an old FDK), the error is logged at the error level. We should log at warning since it is not a platform error and it only affects the function in question.
> Rework call placement/finish logs to take advantage of user blame tag

- api/agent/agent.go
- api/agent/drivers/docker/cookie.go
- api/agent/drivers/docker/docker_test.go
- api/agent/drivers/docker/image_cleaner_test.go
- api/agent/drivers/driver.go
- api/agent/drivers/mock/mocker.go
Users of driver cookie, as seen in agent.go require specific
timeouts in contexts passed to the different operations. For
example, cookie.PullImage() context shows intent to apply
timeout/duration for the pull operation. To clarify this
and avoid tricky timeout related issues, removing implicit
docker-inspect in cookie.PullImage(). In addition, separating
the Authentication step as Auther interface calls unknown
code.
Additional changes to cookie implementation to clarify
inspected image, created container and authentication
configuration, where each AuthImage(), ValidateImage()
and CreateContainer() steps initialize the corresponding
pointer object in the cookie.
Changes now require ValidateImage() call if a PullImage()
is attempted. In all cases, AuthImage() call is required
before …
> fn: driver cookie interface changes for finer control

- fnext/datastore.go
Closes: #1386
- What I did
Changed var reference
- How I did it
Wasn't too hard to spot the problem.
Write a new fn extension and ensure that you have correct function instance.
Fixing AfterFnCreate/AfterFnUpdate fn references.
> Fix AfterFnCreate/AfterFnUpdate actions

- api/agent/agent.go
- api/agent/drivers/docker/docker_pool.go
- api/agent/drivers/docker/docker_test.go
- api/agent/drivers/driver.go
- api/server/runner_fninvoke_test.go
Removing hello-world, fnproject/hello images from tests.
In drivers.ContainerTask Timeout is obsoleted code from cold
containers, which we no longer have.
> fn: remove old test related images

- api/agent/drivers/docker/cookie.go
Classify docker pull errors as user errors and adjust log level
accordingly.
> fn: docker-pull errors are user errors

- Makefile
- api/agent/agent.go
- api/agent/config.go
- api/agent/drivers/docker/cookie.go
- api/agent/drivers/docker/docker_test.go
- api/agent/drivers/driver.go
- images/fn-test-volume/Dockerfile
- images/fn-test-volume/build.sh
- What I did
Added validation to check function image for VOLUME definitions, reject to run if VOLUME is present.
Try to run an image with VOLUME defined.
Function image can't contain VOLUME definition
> Prevent in-built docker VOLUME commands

- api/agent/agent.go
- api/agent/agent_test.go
- api/agent/call.go
- api/agent/drivers/docker/cookie.go
- api/agent/drivers/docker/docker.go
- api/agent/drivers/docker/docker_test.go
- api/agent/drivers/docker/image_cleaner_test.go
- api/agent/drivers/driver.go
- api/agent/drivers/mock/mocker.go
this patch accomplishes a few things wrt the docker auth interface used for
configuring credentials to be used for pull:
* adds context for timing out the docker auth call
* no longer call docker auth before validating an image, we were using this to
validate that a user still has access to an image that we have locally. this
policy itself could be TBD but we're being flagged for hitting registries too
hard, and runners have bounded lifetimes on the order of hours, so we decided
this is ok. now we only call docker auth function when pulling an image, and
it's time used is included in the pull timeout we've so delicately plumbed
* adds ability for agents to add call configurations to every call created via
getcall, this ought to help allow fn extenders configure calls and puts us on
the …
> plumb docker auther to the depths

- api/agent/agent.go
- api/agent/agent_test.go
- api/agent/config.go
- api/agent/drivers/docker/cookie.go
- api/agent/drivers/docker/docker.go
- api/agent/drivers/docker/docker_client.go
- api/agent/drivers/driver.go
Cleanup of docker retry error handling logic. The code
is likely due to older less stable docker versions. Instead,
we would like to expose any underlying issues and fix them
as necessary.
Examination of logs/events from last 3-4 weeks do not
show any occurrence of retries/errors and on the contrary
causing more issues (eg. retry of docker-pull if 5xx)
> fn: clean docker retry logic and legacy code

- api/agent/drivers/docker/docker.go
- api/agent/drivers/docker/docker_test.go
syslog error is treated as an user error, it is still returned as 500, but with "Syslog Unavailable" message.
> Handle syslog error

- api/agent/call.go
- api/agent/lb_agent.go
- test/fn-system-tests/system_test.go
With this change CallOverrider get the request as its first parameter.
We know that we want to get rid of it but there are some cases where the
CallOverrider at the moment is the only place where we can customize a
call before it gets executed until we find a solution for the problem
reported in issue #1426.
Having access to the original request it could be handy during in
CallOverrider.
> Pass Request to CallOverrider

- api/agent/drivers/docker/cookie.go
- api/agent/drivers/docker/docker.go
- api/agent/drivers/docker/image_puller.go
- api/agent/drivers/docker/image_puller_test.go
Due to unnecessary http traffic caused by docker internally, with
this PR a new image pull layer is introduced. This allows us to
serialize same image docker pulls using a simple active transfer
with list of listeners model.
The timeout behavior is slightly different when multiple listeners
are waiting. The timeout from first listener is emitted to all
listeners. However since the docker-pull timeout is globally
configured, overall timeout behavior is essentially the same.
> fn: introducing a new image pull layer

- api/agent/drivers/docker/docker.go
- api/agent/drivers/docker/docker_client.go
- api/agent/drivers/docker/image_puller.go
- api/agent/drivers/docker/image_puller_test.go
- api/agent/drivers/driver.go
- api/agent/drivers/mock/mocker.go
- api/agent/hybrid/client.go
- api/common/backoff.go
- api/common/backoff_test.go
- api/server/hybrid.go
- test/fn-system-tests/system_test.go
Introducing SetPullImageRetryPolicy() for docker driver to allow
customizations of docker pull behavior.
Replacing old backoff code with a more formal exponential backoff
with policy options.
> fn: docker pull retry / backoff options

- api/agent/agent.go
- api/agent/drivers/docker/docker_pool.go
- api/agent/drivers/docker/docker_test.go
- api/agent/drivers/driver.go
This is useful to determine which call is about to run or
last call that was run on that container.
> fn: add getter/setter for last/current call id in a container

- api/server/init.go
- api/server/server.go
currently the fn server uses default http server settings such as timeouts and limits on header sizes.
This change enables setting them using environment variables, but if not set, default values will be used.
> To Enable configuring http server settings through env

- api/agent/agent.go
- api/agent/config.go
- api/agent/state_trackers.go
- api/agent/stats.go
- cmd/fnserver/main.go
in main we wire in view tags, so for OSS we can wire these tags in by default
and anybody that builds their own version of fn that doesn't want them can
easily turn them off (I did this, and it works as expected, the tags don't
appear in prometheus). I think we probably want to add these tags in more
places, but for purpose of discussion and closing out for the metrics we want,
I'm okay with starting out with a limited set of metrics.
I'll say that the symmetry of wiring them into the agent to optionally turn
them on in main seems somewhat appealing though slightly odd specifically for
cases where certain sets of metrics may have different sets of tags. it seems
like we should bundle metrics by what tags they offer, and allow configuring
views that way. I have not gotten into the weeds on …
> add app/fn id and image to container metrics

- api/agent/drivers/docker/registry.go
- api/agent/drivers/docker/registry_test.go
see the linked issue for a good example, it's kind of confusing. docker
defaults to not using a scheme, but the way we were preprocessing registry
urls meant that we were doing this incorrectly (it would parse out `u.Host = ''`
which is incorrect), even though we should allow this since it's dockers own
format and the registry parser itself allows this.
it seems like the reason we're pre-processing is for the subdomain logic,
which kind of makes sense, though it exhibits odd behaviors when specifying a
registry like `registry.com` when only 2 subdomains `raw.registry.com` and
`my.registry.com` have been registered, it's not deterministic between reboots
which credentials will be used, not sure how to reconcile this, I was unable
to find an issue pointing to why this came into existence …
> allow private registries to specify raw host

- api/id/id.go
- api/id/id_test.go
Useful for Fn implementers to validate encoded call ids.
> fn: added a simple validation function for encoded IDs

- api/models/app.go
- api/models/app_test.go
- api/models/fn.go
- api/models/fn_test.go
- api/models/trigger.go
- api/models/trigger_test.go
Extracting the name validation functionality from the models' validators means we can use them else where. In particular this means we can use them to validate user input in the CLI without duplicating the logic c.f. fnproject/cli#474
This is a prerequisite for my changes in fnproject/cli#474
The full explaination can be found [here](https://github.com/fnproject/cli/issues/474#issuecomment-478509980). In particular this commit seperates the name validation from `models.App`, `models.Fn`, and `models.Trigger` `Validate` functions so that they can be called independently. 
```
cd $GOPATH/src/github.com/fnproject/fn/api/models/
go test
```
```
fn := models.Fn{Name: name}
fn.ValidateName()
fn.Validate()
```
```
app := models.App{Name: name}
app.ValidateName()
app.Validate()
```
```
trigger := …
```
> Extract name validation from model validators

- api/server/init.go
- api/server/server.go
this moves initialization up to the init() level as some packages were using
this to create ids before server.New() was called/finished (concurrency!), and
there was a race condition between setting this and creating ids.  this ought
to be sufficient while we're using the host ip address to seed these things,
that day may not last forever but at least this closes the hole for now.
> initialize ids in init

- api/agent/agent.go
When passing call data to container task deep
copy the maps to avoid date race. The call
is not necessarily guaranteed to be scheduled
on that container task and extensions/config
map get modified while read.
> fn-dataplane: fix data race in extensions/config

- api/models/app.go
- api/models/app_test.go
- api/models/error.go
- api/models/fn.go
- api/models/fn_test.go
- api/models/trigger.go
- api/models/trigger_test.go
- api/server/apps_test.go
- api/server/fns_test.go
- api/server/trigger_test.go
was 30, now 255. the service validates the same value, via a different method,
for each of these already. sql uses varchar 256 so we're good. can't think of
any other ways this might break, so going for it.
closes #1452
> increase app/fn/trigger length caps

- api/agent/agent.go
- api/agent/call.go
Container ID is logged inconsistently as `container_id` and `id` in
"call started" and "hot function terminating" messages. `id` is also
used elsewhere for Call ID. Change them all to `container_id` and
`call_id` for consistency.
> Use consistent log field for call and container ID

- api/agent/agent.go
- api/server/gin_middlewares.go
- api/server/server.go
* jaeger deprecated config stuff
* add call_id trace tag, proper app and fn trace span attributes
turns out the tag keys don't get added to the trace span attributes, have to
annotate them differently, kinda sucks but whatever... these are useful for
debugging (particularly call id for me right now, anyway)
> update tracing stuff

- api/agent/data_access.go
- api/datastore/internal/datastoreutil/metrics.go
- api/server/runner_fninvoke.go
- api/server/server.go
currently, the lb read cache only covers apps. however, the API itself can be [and is] used for fns, app ids and triggers, as well. without using the read cache, this means that we were hitting the datastore every invoke request to get the function and the app id, which resulted in added latency due to contention and costs there. get about a 20-30% throughput bump by doing this, and it seems like a pretty obvious thing to do - my load test has functions that run in about 1ms themselves in a not under duress fn environment, making the 5s window coverage a considerable reduction in db calls (like 10k less, in tests, since i'm running 10k in about 10s now it's about 2 db calls instead of 10k)
note that this does affect the service upstream, as the service uses this as well. this means that …
> lb read cache everything under it

- api/agent/agent.go
- api/agent/config.go
- api/agent/drivers/docker/cookie.go
- api/agent/drivers/docker/docker.go
- api/agent/drivers/docker/docker_test.go
- api/agent/drivers/driver.go
- api/models/call.go
- What I did
Add ability to set a max number of PID's that a function is able to use. 
- How I did it
During the call to the Docker daemon to create a new container, a new parameter is passed along which limits the amount of PIDs. This in turn will make the Docker daemon create the new container in a PID namespace with the specified max number of PIDs.
Start the fn server with a env file which contains the following envvar: `FN_MAX_PIDS=100` (change 100 to however much you want the max to be). If debug is turned on a new message which show up when invoking the function (see https://github.com/fnproject/fn/compare/pid_limit#diff-12105267fd0158c3cd4226a828827257R124)
Allow max number of PIDs to be specified
> Add PID limit

- api/agent/runner_client.go
We are currently logging at error level for individual placement
failures which could be retried and could still succeed. This makes the
maximum log level for a per-placement-attempt failure a warning, and
reduces runner 503s to info level (since they are expected if the system
is under any kind of load)
> Change individual placement failure to warning

- api/agent/drivers/register.go
- api/common/env.go
- api/datastore/sql/dbhelper/dbhelper.go
- api/server/init.go
- api/server/server.go
- cmd/fnserver/main.go
we're using json as the log format, and there were various issues in startup
where when setting FN_LOG_FORMAT, a few messages would not be in json format.
this fixes those cases in this repo, but may not for any packages that extend
fn due to initialization order of go (in particular, packages that log
anything in init() may or may not come before this is set, we have little
control over this except for playing with package names, yes, it's mad)
* we were logging a giant ascii fn. i guess this is cool but it doesn't really
matter, just moved it into a logrus line so that we don't have to fight over
it. call me a peace maker
* we were setting the log level/format/destination when initializing the
server, but many packages initialize themselves before calling server.New, and
those may log …
> fix init logging

- api/agent/agent.go
We stumbled over a problem where *some* FDKs are idling their UDS HTTP
connections at periods lower than the 120s that this was expecting.
This was giving rise to spurious errors (from older versions of the node
FDK, for instance) - where invocations beyond the first were seeing
502 gateway errors from a prematurely-closed UDS socket.
The notion of an idle timeout here is good, but we should check that all
FDKs have the appropriate behaviour and give users time to rev their
functions before reintroducing this.
I used a node-FDK-based "hello world" from prior to the fix https://github.com/fnproject/fdk-node/pull/26 like this:
```
fn invoke jang node; sleep 6; fn invoke jang node
```
Before:
```
% fn invoke jang node; sleep 6; fn invoke jang node
{"message":"Hello …
```
> Revert the runner-side idle timeout to 1s

- api/agent/agent.go
- api/agent/config.go
- api/agent/drivers/docker/cookie.go
- api/agent/drivers/docker/docker.go
- api/agent/drivers/driver.go
- api/agent/iofs.go
- images/fn-test-utils/Dockerfile
Runs the function container as user (id:1000, gid:1000) in docker. This requires corresponding changes in base runtime images (add user/group) that are used by the fdks.
It also drops all the security capabilities (by using `CapDrop=all`).
Note that there is an opt-out environment variable `FN_DISABLE_DOCKER_SECURITY` which can be set to true to disable this features.
> run function container as unprivileged user

- api/models/error.go
Currently it's not possible to implement the FuncError interface from packages outside of `models`. This change makes that possible.
> Make it possible to implement FuncError from other packages

- api/agent/agent.go
- api/common/io_utils.go
- api/server/runner_fninvoke_test.go
- api/server/runner_httptrigger.go
- api/server/runner_httptrigger_test.go
we weren't stripping transport headers from function response before copying
to the client response. this means e.g. a function could send a "Connection:
close" when fn wants to use a keep alive.
this also moved this to common since we're doing it in 3 places. I know that
it's not the ideal ideal big O performance and we can pedant about it, but
we're talking about 7 things here. I'm open to ideas about what this should
look like, I ripped it out of the stdlib and it seems okay. changed the
trigger stuff to use this too, as it was copied. added tests to cover all 3 of
these spots.
the only behavior change for existing behavior is no longer stripping 'authorization' header when
passing headers from the client request into the function. authorization seems
like a useful header for users …
> strip transport headers from function response

- Makefile
- api/agent/lb_agent.go
- api/agent/runner_client.go
- api/server/runner_fninvoke.go
- system_test.sh
inside of TryExec we were writing directly to the response writer inside of a
goroutine, but TryExec can timeout and then get called again to a different
runner or even have the front end writing headers while TryExec is writing
headers.
one way to make this safe is to make a new response writer for TryExec to
write the response into, and only after the goroutine handling the response
has returned, from the TryExec goroutine we can copy the response back up as
the caller will not call TryExec again until it has returned (this is
seemingly part of the placer contract). unfortunately, we're already buffering
the response writer in the front end, too - it's possible we can get rid of
that but it may need further testing.
this adds an optimization when copying the request body from the LB to …
> safe responsewriter usage in TryExec

- release.sh
this file was pushing to deprecated refs we don't really need anymore. we
started using the vX.Y.Z to make mod happy and that's widely tracked in VCS
now, whereas I doubt the naked versions are tracked anywhere without something
analogous existing (we've been on mod for some time now).
fnproject/functions was deprecated, and I was only able to find a couple of
stale references (some merely comments). I suspect we can safely remove this.
reduced git pushes from 5 to 1 (woo)
reduced docker pushes from 4 to 1 (yay)
> tidy up release file

- api/agent/agent.go
- api/agent/drivers/docker/image_puller.go
- api/agent/hybrid/client.go
- api/common/time.go
- api/datastore/sql/sql.go
- api/runnerpool/placer_tracker.go
these little guys leak in the background, it's easy enough to remove usage of
them altogether. this reduces cpu load on fn, the main culprit was the one in
waitHot which polls every 200ms. if you run a load test where functions get a
slot and exec a lot faster than 200ms then these things pile up kinda quickly.
> remove usage of time.After

- api/agent/drivers/docker/docker.go
CreateContainerOptions are now initialized with empty NetworkingConfig, this allows changes to NetworkingConfig if needed.
> init CreateContainerOptions with empty NetworkingConfig

- Makefile
- api/server/error_response.go
- api/server/extension_points.go
- api/server/gin_middlewares.go
- api/server/hybrid.go
- api/server/server.go
- examples/extensions/main.go
- fnext/api.go
- fnext/context.go
- fnext/listeners.go
- fnext/setup.go
* changes v1 to v2 for adding an endpoint
* removed the handler funcs for adding handlers onto eg /apps/:app_id/x, we
don't have them for funcs or triggers, and they honestly seem useless as it's
easy to build it with the ability to add a handler and to access the fnext
datastore which we offer, as they were they are really expensive since they
yank the app out of the db even if the operation may not even need it in that
handler. so instead of adding for the rest, remove all of these. none of our
example extensions, which aren't working at the moment, use these either
(that's why I'm here anyway).
* removes dead code helpers and references to app name url param which is no
longer a thing. these were just hanging around bugging me when I ran into
them, so killing them..
> remove unused extensions cruft

- api/agent/drivers/docker/cookie.go
This changes fixes the following logging message by docker:
`Security options with `:` as a separator are deprecated and will be completely unsupported in 17.04, use `=` instead.`
The message was coming from the error is coming from here:
https://github.com/docker/docker-ce/blob/2ba8f3d83c15d3cb018c80e724efe14e3726512f/components/engine/daemon/daemon_unix.go#L228
using security option as 
`c.opts.HostConfig.SecurityOpt = []string{"no-new-privileges"}`
removes the problem
> fix docker security options

- api/agent/drivers/driver.go
- api/agent/drivers/driver_test.go
Currently if image digest is specified on a function image the runner
will ignore it during the docker pull, then fail to execute the function
because the image is not present.
Add awareness of image digests to the pull process to resolve this.
> Support specifying image digest on functions

- Makefile
When we migrated from dep to mod we updated the .PHONY targets but not
the actual target names in the Makefile. Fix this.
> Fix typos in Makefile from go mod migration

- api/agent/pure_runner.go
Some deployments page on errors in logs; let's make sure the errors are
really worth watching.
Ensure that we log nothing in the case that the remote side cancels its
context.  If the checker itself fails, log at warn level instead of
error.
Log status checker errors in pure runner as warnings and not errors.
> Clean up status checker error handling

- api/agent/drivers/driver.go
- api/agent/drivers/driver_test.go
The commit "Support specifying image digest on functions (#1509)"
attempted to fix a problem in the runner that occurs when functions that
include both a digest and a tag are invoked.  In certain cases, the
invocation will fail.  This change fixes one aspect of the problem: the
image string parsing.  However, it overlooks other areas where support
for image digests are needed.  This includes the image cache and the
inspection logic.
To further confuse matters, this change makes it harder to observe and
reproduce the original problem.  This makes it difficult to fully
understand both all of the causes and all of the places that require
fixing up.  Remove this for now with the understanding that it will
probably be required as part of a larger fix to simultaneously handle
tags and digests …
> Backout #1509; needs more work.

- Dockerfile
Docker images have the notion of exposed ports. This indicates the
ports on which a container listens for connections. For the current
fnserver image this is the port 2375 with it inherits from the
fnproject/dind base image.
This confuses end users and other software (reverse proxies) that
expect the fnserver api at this port when inspecting the image/container.
For now it is not possible to remove/unset ports exposed by a base
image but this mr at least adds the default fnserver port to the list
of exposed ports.
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#expose
> Add default fnserver port to the docker image exposed ports

- api/agent/drivers/docker/docker.go
The image field is used to log the name of the image tag during pulls and in a few other places, this change just renames it so we don't conflict with it being both a string and a complex object.
> Remove conflicting structured logging

- api/agent/agent.go
- api/agent/lb_agent.go
https://github.com/fnproject/fn/issues/1517
Added fn appid and fnid (needed for internal tracing), and corrected span name in lb_agent.go to avoid duplicate span conflict with span in agent.go
https://github.com/fnproject/fn/blob/1fb78ed8362693105aee48a506129e6776d1a3a8/api/agent/lb_agent.go#L200
https://github.com/fnproject/fn/blob/4ccd8fa0c63e65aa4b35c1f76cbd7db919f59c7c/api/agent/agent.go#L250
It's gonna look like this
Changing duplicate span name
> Changing lb_agent span name, attrib (#1517)

- Makefile
- api/agent/lb_agent.go
- api/agent/runner_client.go
- api/server/runner_fninvoke.go
- system_test.sh
This reverts commit 1fb78ed8362693105aee48a506129e6776d1a3a8.
This PR  reverts #1490 
- What I did
git revert 1fb78ed8362693105aee48a506129e6776d1a3a8
- How I did it
git revert 1fb78ed8362693105aee48a506129e6776d1a3a8
Ensure tests are passing.
Revert #1490 as this was breaking detached function calls. The new code was writing http response to a copy of response writer, which prevented the lbagent from responding to its client early.
> Revert "safe responsewriter usage in TryExec (#1490)"

- api/agent/runner_client.go
- test/fn-system-tests/exec_fn_test.go
The issue 1484 reported racy test due to concurrent read/write of response headers during TryExec. This PR fixes the issue by making a copy of header before we write and use the copy to read later.
This PR also enhances the system test for detached calls by also verifying that the call returns within 30 seconds even if the function execution takes more than 30 seconds.
https://github.com/fnproject/fn/issues/1484
- What I did
This PR fixes the issue by making a copy of header before we write and use the copy to read later.
- How I did it
This PR fixes the issue by making a copy of header before we write and use the copy to read later.
Run the tests and ensure it does not fail.
Fix 1484 by making a …
> fix-1484: Fix racy test by fixing concurrent header read/write

- api/agent/call.go
- api/agent/lb_agent_test.go
- api/models/call.go
We'd like a better picture of how long we spend running actual user
code. The pure_runner has a decent picture of this; pull that out of
the runner response and feed it back into the *models.Call structure.
- What I did
Captured actual function run time
- How I did it
Believed what the runner said and promoted that value to the models.Call
"Expose the runner-reported execution duration"
> Expose the runner-reported execution duration

- api/agent/agent.go
- api/agent/drivers/docker/docker.go
- api/agent/drivers/driver.go
- api/agent/drivers/mock/mocker.go
- api/agent/lb_agent.go
- api/agent/slots.go
- api/agent/slots_test.go
- test/fn-system-tests/system_test.go
When the same call is invoked with changes in the extensions, we end up using the old cached values if we reuse a slot 
Included call extensions in the slot key so that we match and reuse a slot only if the extensions do not change
> use a new slot if call extensions change

- docs/swagger_v2.yml
Function and Trigger creation can both return 404 statuses if the
related objects do not exist. Document these errors in the swagger
specification.
> Include 404 statuses for creations in swagger

- api/agent/drivers/docker/image_cache.go
- api/agent/drivers/driver.go
- api/agent/drivers/driver_test.go
- What I did
Added back the change to pull image using digest. This was reverted temporarily to debug token caching issues in runner
Image name is used in image puller, image cache, image cleaner and slot hash. In most of these place an inspect image is called to get image details from docker daemon. Inspect image api returns the image corresponding to the digest if present in the image name. Image cache code uses the repotags only to identify any special images that should not be cached or expired. Slot Hash will use different containers for functions invoked by tag-only and functions invoked with tag+digest. Overall, the code doesn't seem to use image tags for indexing, but use ID instead. 
Test case summary
Case 1: Pull older digest than repo latest
Invoked a function …
> Adding back the change to pull image by digest

- api/models/error.go
- api/server/runner_fninvoke_test.go
- api/server/runner_httptrigger_test.go
- test/fn-system-tests/exec_fn_test.go
- test/fn-system-tests/exec_http_trigger_test.go
This small change makes some modifications to the error messages so as
they are more clear and reflect the new version of the code.
- What I did
changed some error messages. 
making the docker pull timeout more generic and change it to image pull timeout.
Remove the mention to function format as we don't have this concept anymre.
Report a more specific error in case of Request body too large.
> Modify error messages

- api/agent/drivers/docker/docker.go
- api/agent/drivers/docker/docker_test.go
- api/models/error.go
We codified the SyslogUnavailable error into a public error exposed by
the models package
> Add SyslogUnavailable as new codified error

- api/agent/pure_runner.go
- api/models/error.go
Catches and generates function errors for two new cases.  The first
occurs due to a function/FDK error.  If the function closes the read end
of the pipe that the hostagent uses to write data before the hostagent
has finished writing the data, generate an error.  This ensures that
any premature close of the input stream is detected and handled by the
hostagent.
Second, catch any cases where the function attempts to respond before
reading all of the input data from the stream.  This is safe because we
already enforce a maximum upper bound on the request body, so a function
or fdk will not have to read for an unbounded amount of time to consume
the outstanding data.  Since the container contract enforces HTTP-like
semantics, and HTTP expects the server side to wait for the response
body to …
> Enforce more rigorous handling of input data and pipes.

- api/agent/agent.go
- api/agent/runner_client.go
Duration units don't need msec conversion for consistency
across, we currently do not do any conversion for execution
duration for example. Newer metrics, ctrPrepTime, imagePullWaitTime,
ctrCreateTime, initStartTime can follow the same.
Remove legacy runner reported duration calculations.
> fn: metrics cleanup

- api/agent/agent.go
- api/agent/resource.go
- api/agent/resource_test.go
Before this change, agent used GetResourceToken() calls
for both non-blocking and blocking mode. However, for
nested calls such as in agent checkLaunch(), a token might
already be queued via go-routine in getResourceTokenNBChan().
If the consuming code in checkLaunch() runs faster, than
it could place another GetResourceToken() call while the
active token is not yet closed. This can result in momentarily
double cpu/mem allocation resulting in 503 or excess wait.
With this PR, resource allocation blocking and non-blocking
interface is changed and ResourceToken is directly returned
without a channel.
> fn: simplify CPU/Memory acquisition to avoid race condition

- api/agent/agent.go
- api/agent/agent_test.go
- api/agent/config.go
- api/agent/slots.go
- api/agent/slots_test.go
- images/fn-test-utils/fn-test-utils.go
Current fn agent (aka runner) tries to communicate
all container start errors to clients. In order to
achieve this, the errors are retained and could be
delivered to clients that did not spawn that container.
This is OK as it tries to be transparent to callers
instead of suppressing or hiding errors. However,
these errors are retained without a time bound which
is not ideal. An old request could trigger an error
and this error can be sent to a client much later time.
With this change, the error retention semantics change.
If an errors occurs during container start and the client
which triggered the container is no longer present, we
log and discard the result.
Broadly, any error that occurs when a request is not 1-1
bound to a container is logged and discarded.
For testing these …
> fn: slot error retention is suboptimal

- api/models/error.go
enables reporting capacity exceeded errors as user errors
> request limit exceeded added to user errors

- api/runnerpool/ch_placer.go
- api/runnerpool/naive_placer.go
- api/runnerpool/placer_tracker.go
Updates the RetryAllBackOff function to fail early when a request to obtain Runners cannot succeed due to an Fn misconfiguration error. This prevents a user having to wait for the maximum timeout (~180s) when the system is misconfigured.
- What I did
1. Updated the `RetryAllBackOff` to accept the error returned by `rp.Runners(ctx, call)`.
2. Added check to not re-try when the error returned by `rp.Runners(ctx, call)` returns a `user configuration error`.
1.  The error is checked to see if it a user configuration error with the ` models.IsFuncError(err)`. This is the same function used to create the `blame user` tag in the existing middleware (with the exception we do not need to check for nullity).
2. Additionally check for an error status of `502` (which …
> Prevent long timeout when invoking a function and the user has misconfigured the environment.

- api/agent/agent.go
- api/agent/agent_test.go
If container before/after callbacks result in errors, the container
should not continue as these errors usually are not recoverable.
> fn: container before/after callback error handling

- api/runnerpool/placer_tracker.go
Having this at ERROR is too noisy, let's decrease it to WARN. In the future we should get the error message into the gin response logging and remove this log line altogether, but I'll leave that for another day.
> Decrease log level of failure to find runners message to WARN

- README.md
Docs issue: https://github.com/fnproject/docs/issues/119
- What I did
Added the link.
- How I did it
Added a 3rd install option.
Previewed it in my editor.
Add Windows CLI install to Quickstart
Roy needs a Windows CLI option.
> Add Windows CLI install to Quickstart

- api/agent/runner_client.go
When LB is processing http headers from flat array representation
in gRPC, it should use http.Header.Add() to grow http headers to
handle header keys with multiple values.
> fn: LB runner client header processing fix

- api/agent/lb_agent_test.go
- api/runnerpool/naive_placer.go
- api/runnerpool/naive_placer_test.go
If naive placer is not instantiated per call/runner group (aka LBG),
then the rr index will not trigger an round-robin behavior since
the index is initialized and stored in the placer configuration.
With this PR, moving rr index to per RunnerPool.Runners() inner loop
to ensure a round robin within that set. Each time we fetch a set,
since the set might be different, we reset our rr index. This means
we rr within that set once, then randomly start from another node
for the next RunnerPool.Runners() iteration. In busy systems,
no significant behavior change is expected (accept the removal of
atomic operations with respect to performance), but in idle systems
round robin behavior should be more observable and simple to follow and can
reduce same hit cases for the given RunnerPool.Runners(). …
> fn: naive placer rr fixup with tests

- api/agent/runner_client.go
Revert runner client to use the Status method on gRPC interface.  This is for environments where different OSS versions are vendored into client and server processes and the server may not have upgraded to the newer version.
> Revert client to using the older(v1) Status method.

- api/agent/lb_agent.go
Even for CLOCK_MONOTONIC, NTP adjustments can be made for advancing
the clock forward. When reporting metrics, let's handle this as
callLatency zero (in other words, execution latency is almost
same as overall latency.)
> fn: handle go-lang time.Now() skew

- .circleci/config.yml
- api/common/logging.go
- api/datastore/datastore.go
- api/datastore/sql/dbhelper/dbhelper.go
- api/datastore/sql/mysql/mysql.go
- api/datastore/sql/postgres/postgres.go
- api/datastore/sql/sql.go
- api/datastore/sql/sql_test.go
- api/datastore/sql/sqlite/sqlite.go
- What I did
Updated the code to build successfully with go1.13. We parsed DB connection strings with url.Parse, but that no longer works with go1.13. I've changed the code to pass the connection strings around as strings. 
Buid with go1.13
> Build with go1.13
